/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState } from "react";
import { useGLTF, PerspectiveCamera, useAnimations, OrbitControls } from "@react-three/drei";
import { useLoader, useFrame, useThree } from "@react-three/fiber";
import { TextureLoader } from "three";
import * as THREE from 'three'

let meshname = 'Default'

let isDragging = false;
let startX
let camTimeScale = 0
let lastXvalue = 0
let xdrag 
let isOpen = false;

const dropdownContent = document.getElementById('dropdown-content');
const sidebarImage = document.getElementById('sidebar');

document.getElementById('sidebar').addEventListener('click', (e) => {
  console.log(isOpen)
 isOpen = !isOpen;
  dropdownContent.style.display =isOpen ? 'block' : 'none';
  // Change the image source based on the dropdown state
  sidebarImage.src =isOpen ? './images/sidebarU.png' : './images/2024.01.29_SURF_PROJECT.NAME_WINDOW.CLOSED-41.png';
});

export function Model(props) {
  const modelRef = useRef()

  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/Test.glb");
  const { actions, mixer } = useAnimations(animations, group);

  let img1 = './images/hotspot.png'
  let img2 = './images/B100.png'; // Change this to the path of your other texture
  let img3 = './images/B200.png'
  let img4 = "./images/B300.png"
  let img5 = "./images/B400.png"
  let img6 = "./images/B500.png"
  let view = "./images/360view.png"



  const [hovered1, setHovered1] = useState(false);
  const [hovered2, setHovered2] = useState(false);
  const [hovered3, setHovered3] = useState(false);
  const [hovered4, setHovered4] = useState(false);
  const [hovered5, setHovered5] = useState(false);




  const hotspottex = useLoader(TextureLoader, img1);
  const hotspottexHovered = useLoader(TextureLoader, img2);
  const hotspottexHovered1 = useLoader(TextureLoader, img3);
  const hotspottexHovered2 = useLoader(TextureLoader, img4);
  const hotspottexHovered3 = useLoader(TextureLoader, img5);
  const hotspottexHovered4 = useLoader(TextureLoader, img6);
  const viewtex = useLoader(TextureLoader, view);

  useEffect(() => void (actions["MainCameraAltActionClip"].play().paused = true), [])
  //   const b100Camera = document.querySelector("#Cam_B100");
  // b100Camera.addEventListener("click", () => {
  //   animateToB100();
  // });

  // useEffect(() => {
  //   void(actions["MainCameraAltActionClip"]).play()
  //   mixer.timeScale = 0.5

  // },[]) 

  window.addEventListener('mousedown', startDrag);
  window.addEventListener('mousemove', drag);
  window.addEventListener('mouseup', stopDrag);

  function startDrag(e) {
    isDragging = true
    startX = e.clientX ;
    // startY = e.clientY;
    console.log("a", startX)

  }

  function drag(e) {
    xdrag = e.clientX - startX;
    xdrag = xdrag + lastXvalue
    // const y = e.clientY - startY;
    if (isDragging) {
      // console.log(x / 1000)
      camTimeScale = xdrag / 1000
    }
    else {
      // console.log("Not ")
    }
    if(xdrag >= 1000){
      xdrag = 0
    } 
    if(xdrag < 0){
      xdrag = 1000
    } 
  }

  function stopDrag(e) {
    lastXvalue = xdrag
    
    isDragging = false
  }

  let camPos = new THREE.Vector3()
  let camRot = new THREE.Vector3()

  const setCameraPosRot = (hotspotname) => {
    switch (hotspotname) {
      case 'B100':
        camPos.x = 12.437;
        camPos.y = 4.9;
        camPos.z = 16.587;
        camRot.x = -0.439;
        camRot.y = 0.715;
        camRot.z = 0.299;
        document.getElementById('bnmtitle').innerText = "Building name"
        document.getElementById('bname').innerText = "B100(B100a+B100b"
        document.getElementById('fareatitle').innerText = "Floor Area"
        document.getElementById('farea').innerText = "2,92,552 sq ft(27,170sq m)"
        document.getElementById('mareatitle').innerText = "Mezzanine Area"
        document.getElementById('marea').innerText = "5,382sq ft(27,640sq m)"
        document.getElementById('totbareatitle').innerText = "Total Buid-up Area"
        document.getElementById('totbarea').innerText = "2,97,837 sq ft(27,640sq m)"
        document.getElementById('clrhgttitle').innerText = "Clear Height"
        document.getElementById('clrhgt').innerText = "12 meters minimum"
        document.getElementById('Usage').style.display = 'none'
        document.getElementById('Usage-P').style.display = 'none'
        break;
      case 'B200':
        camPos.x = 6.601
        camPos.y = 3.308
        camPos.z = 15.383
        camRot.x = -0.309
        camRot.y = -0.625
        camRot.z = -0.184
        document.getElementById('bnmtitle').innerText = "Building name"
        document.getElementById('bname').innerText = "B200(B200a+B200b"
        document.getElementById('fareatitle').innerText = "Floor Area"
        document.getElementById('farea').innerText = "3,05,157 sq ft(28,350 sq m)"
        document.getElementById('mareatitle').innerText = "Mezzanine Area"
        document.getElementById('marea').innerText = "5,382sq ft(500 sq m)"
        document.getElementById('totbareatitle').innerText = "Total Buid-up Area"
        document.getElementById('totbarea').innerText = "3,10,539 sq ft(28,850 sq m)"
        document.getElementById('clrhgttitle').innerText = "Clear Height"
        document.getElementById('clrhgt').innerText = "12 meters minimum"
        document.getElementById('Usage').style.display = 'none'
        document.getElementById('Usage-P').style.display = 'none'

        break;
      case 'B300':
        camPos.x = -2.254
        camPos.y = 4.107
        camPos.z = -10.756
        camRot.x = -2.787
        camRot.y = 0.413
        camRot.z = 2.994
        document.getElementById('bnmtitle').innerText = "Building name"
        document.getElementById('bname').innerText = "B300(B300a+B300b"
        document.getElementById('fareatitle').innerText = "Floor Area"
        document.getElementById('farea').innerText = "2,92,552 sq ft(27,170sq m)"
        document.getElementById('mareatitle').innerText = "Mezzanine Area"
        document.getElementById('marea').innerText = "5,382sq ft(500 sq m)"
        document.getElementById('totbareatitle').innerText = "Total Buid-up Area"
        document.getElementById('totbarea').innerText = "4,13,377 sq ft(38,404 sq m)"
        document.getElementById('clrhgttitle').innerText = "Clear Height"
        document.getElementById('clrhgt').innerText = "12 meters minimum"
        document.getElementById('Usage').style.display = 'none'
        document.getElementById('Usage-P').style.display = 'none'

        break;
      case 'B400':
        camPos.x = -9.624
        camPos.y = 3.417
        camPos.z = -4.656
        camRot.x = -2.567
        camRot.y = -1.043
        camRot.z = -2.632
        document.getElementById('bnmtitle').innerText = "Building name"
        document.getElementById('bname').innerText = "B400(B400a+B400b"
        document.getElementById('fareatitle').innerText = "Floor Area"
        document.getElementById('farea').innerText = "2,92,552 sq ft(27,170sq m)"
        document.getElementById('mareatitle').innerText = "Mezzanine Area"
        document.getElementById('marea').innerText = "5,382sq ft(500 sq m)"
        document.getElementById('totbareatitle').innerText = "Total Buid-up Area"
        document.getElementById('totbarea').innerText = "2,66,363 sq ft(24,746sq m)"
        document.getElementById('clrhgttitle').innerText = "Clear Height"
        document.getElementById('clrhgt').innerText = "12 meters minimum"
        document.getElementById('Usage').style.display = 'none'
        document.getElementById('Usage-P').style.display = 'none'


        break;
      case 'B500':
        camPos.x = -7.068
        camPos.y = 5.436
        camPos.z = 1.633
        camRot.x = -0.595
        camRot.y = -0.578
        camRot.z = -0.354
        document.getElementById('bnmtitle').innerText = "Building name"
        document.getElementById('bname').innerText = "B500(B500a+B500b"
        document.getElementById('fareatitle').innerText = "Floor Area"
        document.getElementById('farea').innerText = "2,92,552 sq ft(27,170sq m)"
        document.getElementById('mareatitle').innerText = "Mezzanine Area"
        document.getElementById('marea').innerText = "5,382sq ft(500 sq m)"
        document.getElementById('totbareatitle').innerText = "Total Buid-up Area"
        document.getElementById('totbarea').innerText = "1,47,186 sq ft(13,674sq m)"
        document.getElementById('clrhgttitle').innerText = "Clear Height"
        document.getElementById('clrhgt').innerText = "12 meters minimum"
        document.getElementById('Usage').style.display = 'none'
        document.getElementById('Usage-P').style.display = 'none'

        


        break;
      case 'Default':
        camPos.x = 31.401
        camPos.y = 13.534
        camPos.z = 42.827
        camRot.x = -0.32
        camRot.y = 0.604
        camRot.z = 0.186

        document.getElementById('bnmtitle').innerText = "Indospace Industrial"
        document.getElementById('bname').innerText = "Warehousing and logistic Park"
        document.getElementById('fareatitle').innerText = "Total Land Parcel"
        document.getElementById('farea').innerText = "186 Acres"
        document.getElementById('mareatitle').innerText = "Plot 1 Land Area"
        document.getElementById('marea').innerText = "62 Acres"
        document.getElementById('totbareatitle').innerText = "Total Chargebale Area"
        document.getElementById('totbarea').innerText = "14,35,315 sq ft(1,33,344 sq m)"
        document.getElementById('clrhgttitle').innerText = "Type Of Land"
        document.getElementById('clrhgt').innerText = "Industrial"
        document.getElementById('Usage').innerText = "Usage"
        document.getElementById('Usage-P').innerText = "Industrial,warehousing and Logistic Park"
        document.getElementById('Usage').style.display = 'block'
        document.getElementById('Usage-P').style.display = 'block'
      

        break;
      default:
        // console.log("Default Case")
    }
    document.getElementById('dropdown-content').style.display = 'block'
    document.getElementById('sidebar').src = './images/sidebarU.png'
    // isOpen = true;
  }

  const closeBtn = document.getElementById('cbtn')

  const perspectiveCam = useRef();
  const maincam1 = useRef()

  // let defaultCam = false

  // const { get, set } = useThree(({ get, set }) => ({ get, set }));

  const [clicked, setClicked] = useState(false)
  const [closed, setClose] = useState(false)

  closeBtn.addEventListener('click', () => {
    closeBtn.style.display = 'none'
    meshname = 'Default'
    setCameraPosRot(meshname)
    setClicked(false)
    setClose(true)
    document.getElementById('dropdown-content').style.display = 'none'
    document.getElementById('sidebar').src = './images/2024.01.29_SURF_PROJECT.NAME_WINDOW.CLOSED-41.png'
    // isOpen = false;
  })
 
  
  // useFrame(state => {
  //   if (clicked3) {
  //     state.camera.lookAt(-0.439, 0.715, 0.299)
  //     state.camera.position.set(12.437, 4.9, 16.587)
  //     state.camera.updateProjectionMatrix()
  //     closeBtn.style.display = 'block'
  //   }
  //   else if (!clicked3) {
  //     state.camera.lookAt(-0.32, 0.604, 0.186)
  //     state.camera.position.set(31.401, 13.534, 42.827)
  //     state.camera.updateProjectionMatrix()
  //   }
  //   return null
  // })

  useFrame(state => {
    console.log(meshname)
    if (clicked) {
      setCameraPosRot(meshname)
      state.camera.rotation.set(camRot.x, camRot.y, camRot.z)
      state.camera.position.set(camPos.x, camPos.y, camPos.z)
      state.camera.updateProjectionMatrix()
      closeBtn.style.display = 'block'
      
    }
    else if (!clicked) {
      if (meshname == 'Default' && closed) {
        console.log('Close false')
        setClose(false)
        // state.camera.lookAt(-0.32, 0.604, 0.186)
        // state.camera.position.set(31.401, 13.534, 42.827)
        // state.camera.updateProjectionMatrix()

        // setTimeout(() => {
        //   setClose(false)

        // }, 3000);
      }
      else if (isDragging) {
       console.log(camTimeScale)

          actions["MainCameraAltActionClip"].time = THREE.MathUtils.lerp(actions["MainCameraAltActionClip"].time, actions["MainCameraAltActionClip"].getClip().duration * camTimeScale, 1)

      }else{
        camTimeScale += 0.00025
        if(camTimeScale >= 1){
          camTimeScale = 0
        } 
        if(camTimeScale < 0){
          camTimeScale = 1
        } 
          
      actions["MainCameraAltActionClip"].time = THREE.MathUtils.lerp(actions["MainCameraAltActionClip"].time, actions["MainCameraAltActionClip"].getClip().duration * camTimeScale, 1)
        modelRef.current.lookAt(state.camera.position)
        
    }



    }
    return null
  })

  return (
    <>
      {/* b500 */}
      <mesh
        name="hotspotClick1"
        position={[-9.6, 2.3, 3.7]}
        rotation={[0, 0, 0]}
        // ref={modelRef}
        
        onClick={() => {
          meshname = 'B500'
          setClicked(true)
          
        }}
        
        onPointerOver={() => setHovered5(true)}
        onPointerOut={() => setHovered5(false)}
        
        scale={6}
      >
        
        <circleGeometry args={[0.07, 32]} />
        <meshBasicMaterial
          map={hovered5 ? hotspottexHovered4 : hotspottex}
          toneMapped={false}
          transparent={true}
          side={THREE.DoubleSide}
        />
      </mesh>
      {/* B100 */}
      <mesh

        position={[1.2, 2.5,9.5]}
        rotation={[0, 0, 0]}
        ref={modelRef}
        onClick={() => {
          meshname = 'B100'
          setClicked(true)
        }}
        onPointerOver={() =>
          setHovered1(true)}
        onPointerOut={() =>
          setHovered1(false)}
        scale={6}

      >
        <circleGeometry args={[0.07, 32]} />
        <meshBasicMaterial
          map={hovered1 ? hotspottexHovered : hotspottex}
          toneMapped={false}
          transparent={true}
          side={THREE.DoubleSide}

        />
      </mesh>

      {/* B300 */}
      <mesh
        position={[1.3, 1.9, 2.3]}
        rotation={[0, 0, 0]}
        ref={modelRef}
        onClick={() => {
          meshname = 'B300'
          setClicked(true)
        }}
        onPointerOver={() => setHovered3(true)}
        onPointerOut={() => setHovered3(false)}
        scale={6}
      >
        <circleGeometry args={[0.07, 32]} />
        <meshBasicMaterial
          map={hovered3 ? hotspottexHovered2 : hotspottex}
          toneMapped={false}
          transparent={true}
          side={THREE.DoubleSide}

        />
      </mesh>

      {/* B400 */}
      <mesh

        position={[2, 2, -4.7]}
        rotation={[0, 0, 0]}
        ref={modelRef}
        onClick={() => {
          meshname = 'B400'
          setClicked(true)
        }}
        onPointerOver={() => setHovered4(true)}
        onPointerOut={() => setHovered4(false)}
        scale={6}
      >
        <circleGeometry args={[0.07, 32]} />
        <meshBasicMaterial
          map={hovered4 ? hotspottexHovered3 : hotspottex}
          toneMapped={false}
          transparent={true}
          side={THREE.DoubleSide}

        />
      </mesh>


      {/* B200 */}

      <mesh

        position={[15.2, 2.5,8]}
        rotation={[0, 0, 0]}
        ref={modelRef}

        onClick={() => {
          meshname = 'B200'
          setClicked(true)
        }}
        onPointerOver={() => setHovered2(true)}
        onPointerOut={() => setHovered2(false)}
       
        scale={6}
      >
        <circleGeometry args={[0.07, 32]} />
        <meshBasicMaterial
          map={hovered2 ? hotspottexHovered1 : hotspottex}

          toneMapped={false}
          transparent={true}
          side={THREE.DoubleSide}

        />
      </mesh>
      {/* 360view 1*/}
      <mesh

        position={[-5.1, 1.2, 13]}
        rotation={[0, 0, 0]}
        onClick={() => (
          console.log('Clicked 360 view'),
          document.getElementById('popupdarkbg').style.display = 'block',
          document.getElementById('popup').style.display = 'block',
          document.getElementById('popupiframe').src = 'https://equanimoustech.com/Indospace/VR1/',
          document.getElementById('dropdown-content').style.display = 'none',
          document.getElementById('sidebar').src = './images/2024.01.29_SURF_STREET.VIEW.01_WINDOW.OPEN-70.png'
        )}
        scale={6}
      >
        <circleGeometry args={[0.07, 32]} />
        <meshBasicMaterial
          map={viewtex}
          toneMapped={false}
          transparent={true}
          side={THREE.DoubleSide}

        />
      </mesh>


      {/* 360view 2*/}
      <mesh

        position={[9.5, 1.1, 12.5]}
        rotation={[0, 0, 0]}
        onClick={() => (
          console.log('Clicked 360 view'),
          document.getElementById('popupdarkbg').style.display = 'block',
          document.getElementById('popup').style.display = 'block',
          document.getElementById('popupiframe').src = 'https://equanimoustech.com/Indospace/VR3/',
          document.getElementById('dropdown-content').style.display = 'none',
          document.getElementById('sidebar').src = './images/2024.01.29_SURF_STREET.VIEW.02_WINDOW.OPEN-71.png'
          

        )}
        
        scale={6}
      >
        <circleGeometry args={[0.07, 32]} />
        <meshBasicMaterial
          map={viewtex}
          toneMapped={false}
          transparent={true}
          side={THREE.DoubleSide}

        />
        
      </mesh>
      

      {/* 360view 3*/}
      <mesh

        position={[2,1.5,-2]}
        rotation={[0, 0, 0]}
        onClick={() => (
          console.log('Clicked 360 view'),
          document.getElementById('popupdarkbg').style.display = 'block',
          document.getElementById('popup').style.display = 'block',
          document.getElementById('popupiframe').src = 'https://equanimoustech.com/Indospace/VR2/',
          document.getElementById('dropdown-content').style.display = 'none',
          document.getElementById('sidebar').src = './images/2024.01.29_SURF_STREET.VIEW.03_WINDOW.OPEN-72.png'
          
        )}
        scale={6}
      >
        <circleGeometry args={[0.07, 32]} />
        <meshBasicMaterial
          map={viewtex}
          toneMapped={false}
          transparent={true}
          side={THREE.DoubleSide}

        />
      </mesh>




      <group ref={group} {...props} dispose={null}>

        <group name="Scene">
          <group name="Chakan_V_Model" scale={2.169}>
            <group name="IM_Car_01001" rotation={[Math.PI, 0, 0]} scale={-0.024}>
              <mesh
                name="Mesh014"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014.geometry}
                material={materials["74body"]}
              />
              <mesh
                name="Mesh014_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_1.geometry}
                material={materials["74basic"]}
              />
              <mesh
                name="Mesh014_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_2.geometry}
                material={materials["74FABRIC"]}
              />
              <mesh
                name="Mesh014_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_3.geometry}
                material={materials["74REK"]}
              />
              <mesh
                name="Mesh014_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_4.geometry}
                material={materials["74tyre"]}
              />
              <mesh
                name="Mesh014_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_5.geometry}
                material={materials["74tyresf"]}
              />
            </group>
            <group
              name="IM_Car_01002"
              position={[0, 0, 0.569]}
              rotation={[Math.PI, 0, 0]}
              scale={-0.024}
            >
              <mesh
                name="Mesh014"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014.geometry}
                material={materials["74body"]}
              />
              <mesh
                name="Mesh014_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_1.geometry}
                material={materials["74basic"]}
              />
              <mesh
                name="Mesh014_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_2.geometry}
                material={materials["74FABRIC"]}
              />
              <mesh
                name="Mesh014_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_3.geometry}
                material={materials["74REK"]}
              />
              <mesh
                name="Mesh014_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_4.geometry}
                material={materials["74tyre"]}
              />
              <mesh
                name="Mesh014_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_5.geometry}
                material={materials["74tyresf"]}
              />
            </group>
            <group
              name="IM_Car_01003"
              position={[-0.57, 0, 6.968]}
              rotation={[Math.PI, 0, Math.PI]}
              scale={0.024}
            >
              <mesh
                name="Mesh014"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014.geometry}
                material={materials["74body"]}
              />
              <mesh
                name="Mesh014_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_1.geometry}
                material={materials["74basic"]}
              />
              <mesh
                name="Mesh014_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_2.geometry}
                material={materials["74FABRIC"]}
              />
              <mesh
                name="Mesh014_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_3.geometry}
                material={materials["74REK"]}
              />
              <mesh
                name="Mesh014_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_4.geometry}
                material={materials["74tyre"]}
              />
              <mesh
                name="Mesh014_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_5.geometry}
                material={materials["74tyresf"]}
              />
            </group>
            <group
              name="IM_Car_01004"
              position={[-0.57, 0, 6.399]}
              rotation={[Math.PI, 0, Math.PI]}
              scale={0.024}
            >
              <mesh
                name="Mesh014"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014.geometry}
                material={materials["74body"]}
              />
              <mesh
                name="Mesh014_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_1.geometry}
                material={materials["74basic"]}
              />
              <mesh
                name="Mesh014_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_2.geometry}
                material={materials["74FABRIC"]}
              />
              <mesh
                name="Mesh014_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_3.geometry}
                material={materials["74REK"]}
              />
              <mesh
                name="Mesh014_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_4.geometry}
                material={materials["74tyre"]}
              />
              <mesh
                name="Mesh014_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_5.geometry}
                material={materials["74tyresf"]}
              />
            </group>
            <group
              name="IM_Car_01005"
              position={[-0.57, 0, 6.968]}
              rotation={[Math.PI, 0, Math.PI]}
              scale={0.024}
            >
              <mesh
                name="Mesh027"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027.geometry}
                material={materials["73body"]}
              />
              <mesh
                name="Mesh027_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_1.geometry}
                material={materials["73basic"]}
              />
              <mesh
                name="Mesh027_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_2.geometry}
                material={materials["73fabric"]}
              />
              <mesh
                name="Mesh027_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_3.geometry}
                material={materials["73rek"]}
              />
              <mesh
                name="Mesh027_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_4.geometry}
                material={materials["73tyresf"]}
              />
              <mesh
                name="Mesh027_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_5.geometry}
                material={materials["73tyresf.002"]}
              />
              <mesh
                name="Mesh027_6"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_6.geometry}
                material={materials["73tyresf.001"]}
              />
            </group>
            <group name="IM_Car_01006" rotation={[Math.PI, 0, 0]} scale={-0.024}>
              <mesh
                name="Mesh027"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027.geometry}
                material={materials["73body"]}
              />
              <mesh
                name="Mesh027_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_1.geometry}
                material={materials["73basic"]}
              />
              <mesh
                name="Mesh027_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_2.geometry}
                material={materials["73fabric"]}
              />
              <mesh
                name="Mesh027_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_3.geometry}
                material={materials["73rek"]}
              />
              <mesh
                name="Mesh027_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_4.geometry}
                material={materials["73tyresf"]}
              />
              <mesh
                name="Mesh027_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_5.geometry}
                material={materials["73tyresf.002"]}
              />
              <mesh
                name="Mesh027_6"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_6.geometry}
                material={materials["73tyresf.001"]}
              />
            </group>
            <group name="IM_Car_01007" rotation={[Math.PI, 0, 0]} scale={-0.024}>
              <mesh
                name="Mesh023"
                castShadow
                receiveShadow
                geometry={nodes.Mesh023.geometry}
                material={materials["75body"]}
              />
              <mesh
                name="Mesh023_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh023_1.geometry}
                material={materials["75basic"]}
              />
              <mesh
                name="Mesh023_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh023_2.geometry}
                material={materials["75fabric"]}
              />
              <mesh
                name="Mesh023_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh023_3.geometry}
                material={materials["75rek"]}
              />
              <mesh
                name="Mesh023_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh023_4.geometry}
                material={materials["75tyre"]}
              />
              <mesh
                name="Mesh023_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh023_5.geometry}
                material={materials["75tyresf"]}
              />
            </group>
            <group name="IM_Car_01008" rotation={[Math.PI, 0, 0]} scale={-0.024}>
              <mesh
                name="Mesh013"
                castShadow
                receiveShadow
                geometry={nodes.Mesh013.geometry}
                material={materials["75body"]}
              />
              <mesh
                name="Mesh013_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh013_1.geometry}
                material={materials["75basic"]}
              />
              <mesh
                name="Mesh013_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh013_2.geometry}
                material={materials["75fabric"]}
              />
              <mesh
                name="Mesh013_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh013_3.geometry}
                material={materials["75rek"]}
              />
              <mesh
                name="Mesh013_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh013_4.geometry}
                material={materials["75tyre"]}
              />
              <mesh
                name="Mesh013_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh013_5.geometry}
                material={materials["75tyresf"]}
              />
            </group>
            <group
              name="IM_Car_01009"
              position={[-0.57, 0, 6.968]}
              rotation={[Math.PI, 0, Math.PI]}
              scale={0.024}
            >
              <mesh
                name="Mesh023"
                castShadow
                receiveShadow
                geometry={nodes.Mesh023.geometry}
                material={materials["75body"]}
              />
              <mesh
                name="Mesh023_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh023_1.geometry}
                material={materials["75basic"]}
              />
              <mesh
                name="Mesh023_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh023_2.geometry}
                material={materials["75fabric"]}
              />
              <mesh
                name="Mesh023_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh023_3.geometry}
                material={materials["75rek"]}
              />
              <mesh
                name="Mesh023_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh023_4.geometry}
                material={materials["75tyre"]}
              />
              <mesh
                name="Mesh023_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh023_5.geometry}
                material={materials["75tyresf"]}
              />
            </group>
            <group
              name="IM_Car_01013"
              position={[-0.57, 0, 6.968]}
              rotation={[Math.PI, 0, Math.PI]}
              scale={0.024}
            >
              <mesh
                name="Mesh013"
                castShadow
                receiveShadow
                geometry={nodes.Mesh013.geometry}
                material={materials["75body"]}
              />
              <mesh
                name="Mesh013_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh013_1.geometry}
                material={materials["75basic"]}
              />
              <mesh
                name="Mesh013_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh013_2.geometry}
                material={materials["75fabric"]}
              />
              <mesh
                name="Mesh013_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh013_3.geometry}
                material={materials["75rek"]}
              />
              <mesh
                name="Mesh013_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh013_4.geometry}
                material={materials["75tyre"]}
              />
              <mesh
                name="Mesh013_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh013_5.geometry}
                material={materials["75tyresf"]}
              />
            </group>
            <group name="IM_Car_01014" position={[2.279, 0, 2.137]} scale={0.024}>
              <mesh
                name="Mesh027"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027.geometry}
                material={materials["73body"]}
              />
              <mesh
                name="Mesh027_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_1.geometry}
                material={materials["73basic"]}
              />
              <mesh
                name="Mesh027_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_2.geometry}
                material={materials["73fabric"]}
              />
              <mesh
                name="Mesh027_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_3.geometry}
                material={materials["73rek"]}
              />
              <mesh
                name="Mesh027_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_4.geometry}
                material={materials["73tyresf"]}
              />
              <mesh
                name="Mesh027_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_5.geometry}
                material={materials["73tyresf.002"]}
              />
              <mesh
                name="Mesh027_6"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_6.geometry}
                material={materials["73tyresf.001"]}
              />
            </group>
            <group name="IM_Car_01015" position={[2.279, 0, 2.137]} scale={0.024}>
              <mesh
                name="Mesh014"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014.geometry}
                material={materials["74body"]}
              />
              <mesh
                name="Mesh014_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_1.geometry}
                material={materials["74basic"]}
              />
              <mesh
                name="Mesh014_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_2.geometry}
                material={materials["74FABRIC"]}
              />
              <mesh
                name="Mesh014_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_3.geometry}
                material={materials["74REK"]}
              />
              <mesh
                name="Mesh014_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_4.geometry}
                material={materials["74tyre"]}
              />
              <mesh
                name="Mesh014_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_5.geometry}
                material={materials["74tyresf"]}
              />
            </group>
            <group
              name="IM_Car_01016"
              position={[-1.25, 0.001, 2.155]}
              rotation={[Math.PI, 0, 0]}
              scale={-0.024}
            >
              <mesh
                name="Mesh027"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027.geometry}
                material={materials["73body"]}
              />
              <mesh
                name="Mesh027_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_1.geometry}
                material={materials["73basic"]}
              />
              <mesh
                name="Mesh027_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_2.geometry}
                material={materials["73fabric"]}
              />
              <mesh
                name="Mesh027_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_3.geometry}
                material={materials["73rek"]}
              />
              <mesh
                name="Mesh027_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_4.geometry}
                material={materials["73tyresf"]}
              />
              <mesh
                name="Mesh027_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_5.geometry}
                material={materials["73tyresf.002"]}
              />
              <mesh
                name="Mesh027_6"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_6.geometry}
                material={materials["73tyresf.001"]}
              />
            </group>
            <group
              name="IM_Car_01017"
              position={[-1.25, 0.001, 2.155]}
              rotation={[Math.PI, 0, 0]}
              scale={-0.024}
            >
              <mesh
                name="Mesh014"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014.geometry}
                material={materials["74body"]}
              />
              <mesh
                name="Mesh014_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_1.geometry}
                material={materials["74basic"]}
              />
              <mesh
                name="Mesh014_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_2.geometry}
                material={materials["74FABRIC"]}
              />
              <mesh
                name="Mesh014_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_3.geometry}
                material={materials["74REK"]}
              />
              <mesh
                name="Mesh014_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_4.geometry}
                material={materials["74tyre"]}
              />
              <mesh
                name="Mesh014_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_5.geometry}
                material={materials["74tyresf"]}
              />
            </group>
            <group
              name="IM_Car_01018"
              position={[-6.201, 0, 1.342]}
              rotation={[0, 1.571, 0]}
              scale={0.024}
            >
              <mesh
                name="Mesh027"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027.geometry}
                material={materials["73body"]}
              />
              <mesh
                name="Mesh027_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_1.geometry}
                material={materials["73basic"]}
              />
              <mesh
                name="Mesh027_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_2.geometry}
                material={materials["73fabric"]}
              />
              <mesh
                name="Mesh027_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_3.geometry}
                material={materials["73rek"]}
              />
              <mesh
                name="Mesh027_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_4.geometry}
                material={materials["73tyresf"]}
              />
              <mesh
                name="Mesh027_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_5.geometry}
                material={materials["73tyresf.002"]}
              />
              <mesh
                name="Mesh027_6"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_6.geometry}
                material={materials["73tyresf.001"]}
              />
            </group>
            <group
              name="IM_Car_01019"
              position={[-6.266, 0, 1.342]}
              rotation={[0, 1.571, 0]}
              scale={0.024}
            >
              <mesh
                name="Mesh014"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014.geometry}
                material={materials["74body"]}
              />
              <mesh
                name="Mesh014_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_1.geometry}
                material={materials["74basic"]}
              />
              <mesh
                name="Mesh014_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_2.geometry}
                material={materials["74FABRIC"]}
              />
              <mesh
                name="Mesh014_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_3.geometry}
                material={materials["74REK"]}
              />
              <mesh
                name="Mesh014_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_4.geometry}
                material={materials["74tyre"]}
              />
              <mesh
                name="Mesh014_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_5.geometry}
                material={materials["74tyresf"]}
              />
            </group>
            <group
              name="IM_Car_01020"
              position={[-6.201, 0, 2.017]}
              rotation={[Math.PI, -1.571, 0]}
              scale={-0.024}
            >
              <mesh
                name="Mesh027"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027.geometry}
                material={materials["73body"]}
              />
              <mesh
                name="Mesh027_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_1.geometry}
                material={materials["73basic"]}
              />
              <mesh
                name="Mesh027_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_2.geometry}
                material={materials["73fabric"]}
              />
              <mesh
                name="Mesh027_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_3.geometry}
                material={materials["73rek"]}
              />
              <mesh
                name="Mesh027_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_4.geometry}
                material={materials["73tyresf"]}
              />
              <mesh
                name="Mesh027_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_5.geometry}
                material={materials["73tyresf.002"]}
              />
              <mesh
                name="Mesh027_6"
                castShadow
                receiveShadow
                geometry={nodes.Mesh027_6.geometry}
                material={materials["73tyresf.001"]}
              />
            </group>
            <group
              name="IM_Car_01021"
              position={[-6.266, 0, 2.017]}
              rotation={[Math.PI, -1.571, 0]}
              scale={-0.024}
            >
              <mesh
                name="Mesh014"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014.geometry}
                material={materials["74body"]}
              />
              <mesh
                name="Mesh014_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_1.geometry}
                material={materials["74basic"]}
              />
              <mesh
                name="Mesh014_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_2.geometry}
                material={materials["74FABRIC"]}
              />
              <mesh
                name="Mesh014_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_3.geometry}
                material={materials["74REK"]}
              />
              <mesh
                name="Mesh014_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_4.geometry}
                material={materials["74tyre"]}
              />
              <mesh
                name="Mesh014_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_5.geometry}
                material={materials["74tyresf"]}
              />
            </group>
            <group name="IM_Car_01022" rotation={[0, 0, -Math.PI]} scale={-0.024}>
              <mesh
                name="Mesh033"
                castShadow
                receiveShadow
                geometry={nodes.Mesh033.geometry}
                material={materials["73body"]}
              />
              <mesh
                name="Mesh033_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh033_1.geometry}
                material={materials["73basic"]}
              />
              <mesh
                name="Mesh033_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh033_2.geometry}
                material={materials["73fabric"]}
              />
              <mesh
                name="Mesh033_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh033_3.geometry}
                material={materials["73rek"]}
              />
              <mesh
                name="Mesh033_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh033_4.geometry}
                material={materials["73tyresf"]}
              />
              <mesh
                name="Mesh033_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh033_5.geometry}
                material={materials["73tyresf.002"]}
              />
              <mesh
                name="Mesh033_6"
                castShadow
                receiveShadow
                geometry={nodes.Mesh033_6.geometry}
                material={materials["73tyresf.001"]}
              />
            </group>
            <group name="IM_Car_01023" rotation={[0, 0, -Math.PI]} scale={-0.024}>
              <mesh
                name="Mesh035"
                castShadow
                receiveShadow
                geometry={nodes.Mesh035.geometry}
                material={materials["74body"]}
              />
              <mesh
                name="Mesh035_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh035_1.geometry}
                material={materials["74basic"]}
              />
              <mesh
                name="Mesh035_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh035_2.geometry}
                material={materials["74FABRIC"]}
              />
              <mesh
                name="Mesh035_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh035_3.geometry}
                material={materials["74REK"]}
              />
              <mesh
                name="Mesh035_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh035_4.geometry}
                material={materials["74tyre"]}
              />
              <mesh
                name="Mesh035_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh035_5.geometry}
                material={materials["74tyresf"]}
              />
            </group>
            <group name="IM_Car_01024" rotation={[0, 0, -Math.PI]} scale={-0.024}>
              <mesh
                name="Mesh036"
                castShadow
                receiveShadow
                geometry={nodes.Mesh036.geometry}
                material={materials["73body"]}
              />
              <mesh
                name="Mesh036_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh036_1.geometry}
                material={materials["73basic"]}
              />
              <mesh
                name="Mesh036_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh036_2.geometry}
                material={materials["73fabric"]}
              />
              <mesh
                name="Mesh036_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh036_3.geometry}
                material={materials["73rek"]}
              />
              <mesh
                name="Mesh036_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh036_4.geometry}
                material={materials["73tyresf"]}
              />
              <mesh
                name="Mesh036_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh036_5.geometry}
                material={materials["73tyresf.002"]}
              />
              <mesh
                name="Mesh036_6"
                castShadow
                receiveShadow
                geometry={nodes.Mesh036_6.geometry}
                material={materials["73tyresf.001"]}
              />
            </group>
            <group name="IM_Car_01025" rotation={[0, 0, -Math.PI]} scale={-0.024}>
              <mesh
                name="Mesh038"
                castShadow
                receiveShadow
                geometry={nodes.Mesh038.geometry}
                material={materials["74body"]}
              />
              <mesh
                name="Mesh038_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh038_1.geometry}
                material={materials["74basic"]}
              />
              <mesh
                name="Mesh038_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh038_2.geometry}
                material={materials["74FABRIC"]}
              />
              <mesh
                name="Mesh038_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh038_3.geometry}
                material={materials["74REK"]}
              />
              <mesh
                name="Mesh038_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh038_4.geometry}
                material={materials["74tyre"]}
              />
              <mesh
                name="Mesh038_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh038_5.geometry}
                material={materials["74tyresf"]}
              />
            </group>
            <group
              name="IM_Car_01026"
              position={[-0.241, 0, 0.496]}
              rotation={[0, 0, -Math.PI]}
              scale={-0.024}
            >
              <mesh
                name="Mesh033"
                castShadow
                receiveShadow
                geometry={nodes.Mesh033.geometry}
                material={materials["73body"]}
              />
              <mesh
                name="Mesh033_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh033_1.geometry}
                material={materials["73basic"]}
              />
              <mesh
                name="Mesh033_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh033_2.geometry}
                material={materials["73fabric"]}
              />
              <mesh
                name="Mesh033_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh033_3.geometry}
                material={materials["73rek"]}
              />
              <mesh
                name="Mesh033_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh033_4.geometry}
                material={materials["73tyresf"]}
              />
              <mesh
                name="Mesh033_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh033_5.geometry}
                material={materials["73tyresf.002"]}
              />
              <mesh
                name="Mesh033_6"
                castShadow
                receiveShadow
                geometry={nodes.Mesh033_6.geometry}
                material={materials["73tyresf.001"]}
              />
            </group>
            <group
              name="IM_Car_01027"
              position={[-0.241, 0, 0.496]}
              rotation={[0, 0, -Math.PI]}
              scale={-0.024}
            >
              <mesh
                name="Mesh035"
                castShadow
                receiveShadow
                geometry={nodes.Mesh035.geometry}
                material={materials["74body"]}
              />
              <mesh
                name="Mesh035_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh035_1.geometry}
                material={materials["74basic"]}
              />
              <mesh
                name="Mesh035_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh035_2.geometry}
                material={materials["74FABRIC"]}
              />
              <mesh
                name="Mesh035_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh035_3.geometry}
                material={materials["74REK"]}
              />
              <mesh
                name="Mesh035_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh035_4.geometry}
                material={materials["74tyre"]}
              />
              <mesh
                name="Mesh035_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh035_5.geometry}
                material={materials["74tyresf"]}
              />
            </group>
            <group
              name="IM_Car_01028"
              position={[-0.241, 0, 0.496]}
              rotation={[0, 0, -Math.PI]}
              scale={-0.024}
            >
              <mesh
                name="Mesh036"
                castShadow
                receiveShadow
                geometry={nodes.Mesh036.geometry}
                material={materials["73body"]}
              />
              <mesh
                name="Mesh036_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh036_1.geometry}
                material={materials["73basic"]}
              />
              <mesh
                name="Mesh036_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh036_2.geometry}
                material={materials["73fabric"]}
              />
              <mesh
                name="Mesh036_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh036_3.geometry}
                material={materials["73rek"]}
              />
              <mesh
                name="Mesh036_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh036_4.geometry}
                material={materials["73tyresf"]}
              />
              <mesh
                name="Mesh036_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh036_5.geometry}
                material={materials["73tyresf.002"]}
              />
              <mesh
                name="Mesh036_6"
                castShadow
                receiveShadow
                geometry={nodes.Mesh036_6.geometry}
                material={materials["73tyresf.001"]}
              />
            </group>
            <group
              name="IM_Car_01029"
              position={[-0.241, 0, 0.496]}
              rotation={[0, 0, -Math.PI]}
              scale={-0.024}
            >
              <mesh
                name="Mesh038"
                castShadow
                receiveShadow
                geometry={nodes.Mesh038.geometry}
                material={materials["74body"]}
              />
              <mesh
                name="Mesh038_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh038_1.geometry}
                material={materials["74basic"]}
              />
              <mesh
                name="Mesh038_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh038_2.geometry}
                material={materials["74FABRIC"]}
              />
              <mesh
                name="Mesh038_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh038_3.geometry}
                material={materials["74REK"]}
              />
              <mesh
                name="Mesh038_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh038_4.geometry}
                material={materials["74tyre"]}
              />
              <mesh
                name="Mesh038_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh038_5.geometry}
                material={materials["74tyresf"]}
              />
            </group>
            <group name="IM_Car_01030" rotation={[0, 1.571, 0]} scale={0.024}>
              <mesh
                name="Mesh040"
                castShadow
                receiveShadow
                geometry={nodes.Mesh040.geometry}
                material={materials["74body"]}
              />
              <mesh
                name="Mesh040_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh040_1.geometry}
                material={materials["74basic"]}
              />
              <mesh
                name="Mesh040_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh040_2.geometry}
                material={materials["74FABRIC"]}
              />
              <mesh
                name="Mesh040_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh040_3.geometry}
                material={materials["74REK"]}
              />
              <mesh
                name="Mesh040_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh040_4.geometry}
                material={materials["74tyre"]}
              />
              <mesh
                name="Mesh040_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh040_5.geometry}
                material={materials["74tyresf"]}
              />
            </group>
            <group
              name="IM_Car_01031"
              rotation={[Math.PI, -1.571, 0]}
              scale={-0.024}
            >
              <mesh
                name="Mesh041"
                castShadow
                receiveShadow
                geometry={nodes.Mesh041.geometry}
                material={materials["73body"]}
              />
              <mesh
                name="Mesh041_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh041_1.geometry}
                material={materials["73basic"]}
              />
              <mesh
                name="Mesh041_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh041_2.geometry}
                material={materials["73fabric"]}
              />
              <mesh
                name="Mesh041_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh041_3.geometry}
                material={materials["73rek"]}
              />
              <mesh
                name="Mesh041_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh041_4.geometry}
                material={materials["73tyresf"]}
              />
              <mesh
                name="Mesh041_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh041_5.geometry}
                material={materials["73tyresf.002"]}
              />
              <mesh
                name="Mesh041_6"
                castShadow
                receiveShadow
                geometry={nodes.Mesh041_6.geometry}
                material={materials["73tyresf.001"]}
              />
            </group>
            <group
              name="IM_Car_01032"
              position={[0.003, 0, 6.192]}
              rotation={[Math.PI, -1.571, 0]}
              scale={-0.024}
            >
              <mesh
                name="Mesh040"
                castShadow
                receiveShadow
                geometry={nodes.Mesh040.geometry}
                material={materials["74body"]}
              />
              <mesh
                name="Mesh040_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh040_1.geometry}
                material={materials["74basic"]}
              />
              <mesh
                name="Mesh040_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh040_2.geometry}
                material={materials["74FABRIC"]}
              />
              <mesh
                name="Mesh040_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh040_3.geometry}
                material={materials["74REK"]}
              />
              <mesh
                name="Mesh040_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh040_4.geometry}
                material={materials["74tyre"]}
              />
              <mesh
                name="Mesh040_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh040_5.geometry}
                material={materials["74tyresf"]}
              />
            </group>
            <group
              name="IM_Car_02001"
              position={[-0.57, 0, 6.968]}
              rotation={[Math.PI, 0, Math.PI]}
              scale={0.024}
            >
              <mesh
                name="Mesh015"
                castShadow
                receiveShadow
                geometry={nodes.Mesh015.geometry}
                material={materials["73body"]}
              />
              <mesh
                name="Mesh015_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh015_1.geometry}
                material={materials["73basic"]}
              />
              <mesh
                name="Mesh015_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh015_2.geometry}
                material={materials["73fabric"]}
              />
              <mesh
                name="Mesh015_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh015_3.geometry}
                material={materials["73rek"]}
              />
              <mesh
                name="Mesh015_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh015_4.geometry}
                material={materials["73tyresf"]}
              />
              <mesh
                name="Mesh015_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh015_5.geometry}
                material={materials["73tyresf.002"]}
              />
              <mesh
                name="Mesh015_6"
                castShadow
                receiveShadow
                geometry={nodes.Mesh015_6.geometry}
                material={materials["73tyresf.001"]}
              />
            </group>
            <group name="IM_Car_02002" rotation={[Math.PI, 0, 0]} scale={-0.024}>
              <mesh
                name="Mesh015"
                castShadow
                receiveShadow
                geometry={nodes.Mesh015.geometry}
                material={materials["73body"]}
              />
              <mesh
                name="Mesh015_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh015_1.geometry}
                material={materials["73basic"]}
              />
              <mesh
                name="Mesh015_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh015_2.geometry}
                material={materials["73fabric"]}
              />
              <mesh
                name="Mesh015_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh015_3.geometry}
                material={materials["73rek"]}
              />
              <mesh
                name="Mesh015_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh015_4.geometry}
                material={materials["73tyresf"]}
              />
              <mesh
                name="Mesh015_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh015_5.geometry}
                material={materials["73tyresf.002"]}
              />
              <mesh
                name="Mesh015_6"
                castShadow
                receiveShadow
                geometry={nodes.Mesh015_6.geometry}
                material={materials["73tyresf.001"]}
              />
            </group>
            <group name="IM_Truck001" scale={0.024}>
              <mesh
                name="model_81001"
                castShadow
                receiveShadow
                geometry={nodes.model_81001.geometry}
                material={materials.backside}
              />
              <mesh
                name="model_81001_1"
                castShadow
                receiveShadow
                geometry={nodes.model_81001_1.geometry}
                material={materials.Body}
              />
              <mesh
                name="model_81001_2"
                castShadow
                receiveShadow
                geometry={nodes.model_81001_2.geometry}
                material={materials.Tires}
              />
            </group>
            <group name="IM_Truck002" position={[-0.286, 0, 0]} scale={0.024}>
              <mesh
                name="model_81001"
                castShadow
                receiveShadow
                geometry={nodes.model_81001.geometry}
                material={materials.backside}
              />
              <mesh
                name="model_81001_1"
                castShadow
                receiveShadow
                geometry={nodes.model_81001_1.geometry}
                material={materials.Body}
              />
              <mesh
                name="model_81001_2"
                castShadow
                receiveShadow
                geometry={nodes.model_81001_2.geometry}
                material={materials.Tires}
              />
            </group>
            <group name="IM_Truck003" position={[-0.568, 0, 0]} scale={0.024}>
              <mesh
                name="model_81001"
                castShadow
                receiveShadow
                geometry={nodes.model_81001.geometry}
                material={materials.backside}
              />
              <mesh
                name="model_81001_1"
                castShadow
                receiveShadow
                geometry={nodes.model_81001_1.geometry}
                material={materials.Body}
              />
              <mesh
                name="model_81001_2"
                castShadow
                receiveShadow
                geometry={nodes.model_81001_2.geometry}
                material={materials.Tires}
              />
            </group>
            <group name="IM_Truck004" position={[-0.847, 0, 0]} scale={0.024}>
              <mesh
                name="model_81001"
                castShadow
                receiveShadow
                geometry={nodes.model_81001.geometry}
                material={materials.backside}
              />
              <mesh
                name="model_81001_1"
                castShadow
                receiveShadow
                geometry={nodes.model_81001_1.geometry}
                material={materials.Body}
              />
              <mesh
                name="model_81001_2"
                castShadow
                receiveShadow
                geometry={nodes.model_81001_2.geometry}
                material={materials.Tires}
              />
            </group>
            <group name="IM_Truck005" position={[-1.123, 0, 0]} scale={0.024}>
              <mesh
                name="model_81001"
                castShadow
                receiveShadow
                geometry={nodes.model_81001.geometry}
                material={materials.backside}
              />
              <mesh
                name="model_81001_1"
                castShadow
                receiveShadow
                geometry={nodes.model_81001_1.geometry}
                material={materials.Body}
              />
              <mesh
                name="model_81001_2"
                castShadow
                receiveShadow
                geometry={nodes.model_81001_2.geometry}
                material={materials.Tires}
              />
            </group>
            <group name="IM_Truck006" scale={0.024}>
              <mesh
                name="model_81005"
                castShadow
                receiveShadow
                geometry={nodes.model_81005.geometry}
                material={materials.backside}
              />
              <mesh
                name="model_81005_1"
                castShadow
                receiveShadow
                geometry={nodes.model_81005_1.geometry}
                material={materials.Body}
              />
              <mesh
                name="model_81005_2"
                castShadow
                receiveShadow
                geometry={nodes.model_81005_2.geometry}
                material={materials.Tires}
              />
            </group>
            <group name="IM_Truck007" position={[-0.269, 0, 0]} scale={0.024}>
              <mesh
                name="model_81005"
                castShadow
                receiveShadow
                geometry={nodes.model_81005.geometry}
                material={materials.backside}
              />
              <mesh
                name="model_81005_1"
                castShadow
                receiveShadow
                geometry={nodes.model_81005_1.geometry}
                material={materials.Body}
              />
              <mesh
                name="model_81005_2"
                castShadow
                receiveShadow
                geometry={nodes.model_81005_2.geometry}
                material={materials.Tires}
              />
            </group>
            <group name="IM_Truck008" position={[-0.642, 0, 0]} scale={0.024}>
              <mesh
                name="model_81005"
                castShadow
                receiveShadow
                geometry={nodes.model_81005.geometry}
                material={materials.backside}
              />
              <mesh
                name="model_81005_1"
                castShadow
                receiveShadow
                geometry={nodes.model_81005_1.geometry}
                material={materials.Body}
              />
              <mesh
                name="model_81005_2"
                castShadow
                receiveShadow
                geometry={nodes.model_81005_2.geometry}
                material={materials.Tires}
              />
            </group>
            <group name="IM_Truck009" position={[0.3, 0, 0]} scale={0.024}>
              <mesh
                name="model_81005"
                castShadow
                receiveShadow
                geometry={nodes.model_81005.geometry}
                material={materials.backside}
              />
              <mesh
                name="model_81005_1"
                castShadow
                receiveShadow
                geometry={nodes.model_81005_1.geometry}
                material={materials.Body}
              />
              <mesh
                name="model_81005_2"
                castShadow
                receiveShadow
                geometry={nodes.model_81005_2.geometry}
                material={materials.Tires}
              />
            </group>
            <group name="IM_Truck014" scale={0.024}>
              <mesh
                name="model_81014"
                castShadow
                receiveShadow
                geometry={nodes.model_81014.geometry}
                material={materials.backside}
              />
              <mesh
                name="model_81014_1"
                castShadow
                receiveShadow
                geometry={nodes.model_81014_1.geometry}
                material={materials.Body}
              />
              <mesh
                name="model_81014_2"
                castShadow
                receiveShadow
                geometry={nodes.model_81014_2.geometry}
                material={materials.Tires}
              />
            </group>
            <group name="IM_Truck015" position={[0, 0, -0.381]} scale={0.024}>
              <mesh
                name="model_81014"
                castShadow
                receiveShadow
                geometry={nodes.model_81014.geometry}
                material={materials.backside}
              />
              <mesh
                name="model_81014_1"
                castShadow
                receiveShadow
                geometry={nodes.model_81014_1.geometry}
                material={materials.Body}
              />
              <mesh
                name="model_81014_2"
                castShadow
                receiveShadow
                geometry={nodes.model_81014_2.geometry}
                material={materials.Tires}
              />
            </group>
            <group name="IM_Truck016" position={[0, 0, -0.754]} scale={0.024}>
              <mesh
                name="model_81014"
                castShadow
                receiveShadow
                geometry={nodes.model_81014.geometry}
                material={materials.backside}
              />
              <mesh
                name="model_81014_1"
                castShadow
                receiveShadow
                geometry={nodes.model_81014_1.geometry}
                material={materials.Body}
              />
              <mesh
                name="model_81014_2"
                castShadow
                receiveShadow
                geometry={nodes.model_81014_2.geometry}
                material={materials.Tires}
              />
            </group>
            <group name="IM_Truck017" position={[0, 0, -1.134]} scale={0.024}>
              <mesh
                name="model_81014"
                castShadow
                receiveShadow
                geometry={nodes.model_81014.geometry}
                material={materials.backside}
              />
              <mesh
                name="model_81014_1"
                castShadow
                receiveShadow
                geometry={nodes.model_81014_1.geometry}
                material={materials.Body}
              />
              <mesh
                name="model_81014_2"
                castShadow
                receiveShadow
                geometry={nodes.model_81014_2.geometry}
                material={materials.Tires}
              />
            </group>
            <group name="IM_Truck018" scale={0.024}>
              <mesh
                name="model_81028"
                castShadow
                receiveShadow
                geometry={nodes.model_81028.geometry}
                material={materials.backside}
              />
              <mesh
                name="model_81028_1"
                castShadow
                receiveShadow
                geometry={nodes.model_81028_1.geometry}
                material={materials.Body}
              />
              <mesh
                name="model_81028_2"
                castShadow
                receiveShadow
                geometry={nodes.model_81028_2.geometry}
                material={materials.Tires}
              />
            </group>
            <group name="IM_Truck019" position={[0.369, 0, 0]} scale={0.024}>
              <mesh
                name="model_81028"
                castShadow
                receiveShadow
                geometry={nodes.model_81028.geometry}
                material={materials.backside}
              />
              <mesh
                name="model_81028_1"
                castShadow
                receiveShadow
                geometry={nodes.model_81028_1.geometry}
                material={materials.Body}
              />
              <mesh
                name="model_81028_2"
                castShadow
                receiveShadow
                geometry={nodes.model_81028_2.geometry}
                material={materials.Tires}
              />
            </group>
            <group name="IM_Truck020" position={[0.646, 0, 0]} scale={0.024}>
              <mesh
                name="model_81028"
                castShadow
                receiveShadow
                geometry={nodes.model_81028.geometry}
                material={materials.backside}
              />
              <mesh
                name="model_81028_1"
                castShadow
                receiveShadow
                geometry={nodes.model_81028_1.geometry}
                material={materials.Body}
              />
              <mesh
                name="model_81028_2"
                castShadow
                receiveShadow
                geometry={nodes.model_81028_2.geometry}
                material={materials.Tires}
              />
            </group>
            <group name="IM_Truck021" scale={0.024}>
              <mesh
                name="model_81021"
                castShadow
                receiveShadow
                geometry={nodes.model_81021.geometry}
                material={materials.backside}
              />
              <mesh
                name="model_81021_1"
                castShadow
                receiveShadow
                geometry={nodes.model_81021_1.geometry}
                material={materials.Body}
              />
              <mesh
                name="model_81021_2"
                castShadow
                receiveShadow
                geometry={nodes.model_81021_2.geometry}
                material={materials.Tires}
              />
            </group>
            <group name="IM_Truck022" position={[0.365, 0, 0]} scale={0.024}>
              <mesh
                name="model_81021"
                castShadow
                receiveShadow
                geometry={nodes.model_81021.geometry}
                material={materials.backside}
              />
              <mesh
                name="model_81021_1"
                castShadow
                receiveShadow
                geometry={nodes.model_81021_1.geometry}
                material={materials.Body}
              />
              <mesh
                name="model_81021_2"
                castShadow
                receiveShadow
                geometry={nodes.model_81021_2.geometry}
                material={materials.Tires}
              />
            </group>
            <group name="IM_Truck023" position={[0.635, 0, 0]} scale={0.024}>
              <mesh
                name="model_81021"
                castShadow
                receiveShadow
                geometry={nodes.model_81021.geometry}
                material={materials.backside}
              />
              <mesh
                name="model_81021_1"
                castShadow
                receiveShadow
                geometry={nodes.model_81021_1.geometry}
                material={materials.Body}
              />
              <mesh
                name="model_81021_2"
                castShadow
                receiveShadow
                geometry={nodes.model_81021_2.geometry}
                material={materials.Tires}
              />
            </group>
            <group
              name="IM_Truck024"
              position={[2.37, 0.056, 4.371]}
              rotation={[-Math.PI, 0, 0]}
              scale={-0.021}
            >
              <mesh
                name="model_81014"
                castShadow
                receiveShadow
                geometry={nodes.model_81014.geometry}
                material={materials.backside}
              />
              <mesh
                name="model_81014_1"
                castShadow
                receiveShadow
                geometry={nodes.model_81014_1.geometry}
                material={materials.Body}
              />
              <mesh
                name="model_81014_2"
                castShadow
                receiveShadow
                geometry={nodes.model_81014_2.geometry}
                material={materials.Tires}
              />
            </group>
            <group
              name="IM_Truck025"
              position={[2.37, 0.056, 3.995]}
              rotation={[-Math.PI, 0, 0]}
              scale={-0.021}
            >
              <mesh
                name="model_81014"
                castShadow
                receiveShadow
                geometry={nodes.model_81014.geometry}
                material={materials.backside}
              />
              <mesh
                name="model_81014_1"
                castShadow
                receiveShadow
                geometry={nodes.model_81014_1.geometry}
                material={materials.Body}
              />
              <mesh
                name="model_81014_2"
                castShadow
                receiveShadow
                geometry={nodes.model_81014_2.geometry}
                material={materials.Tires}
              />
            </group>
            <group
              name="IM_Truck027"
              position={[2.37, 0.056, 3.238]}
              rotation={[-Math.PI, 0, 0]}
              scale={-0.021}
            >
              <mesh
                name="model_81014"
                castShadow
                receiveShadow
                geometry={nodes.model_81014.geometry}
                material={materials.backside}
              />
              <mesh
                name="model_81014_1"
                castShadow
                receiveShadow
                geometry={nodes.model_81014_1.geometry}
                material={materials.Body}
              />
              <mesh
                name="model_81014_2"
                castShadow
                receiveShadow
                geometry={nodes.model_81014_2.geometry}
                material={materials.Tires}
              />
            </group>
            <group
              name="IM_Truck029"
              position={[2.37, 0.056, 2.57]}
              rotation={[-Math.PI, 0, 0]}
              scale={-0.021}
            >
              <mesh
                name="model_81014"
                castShadow
                receiveShadow
                geometry={nodes.model_81014.geometry}
                material={materials.backside}
              />
              <mesh
                name="model_81014_1"
                castShadow
                receiveShadow
                geometry={nodes.model_81014_1.geometry}
                material={materials.Body}
              />
              <mesh
                name="model_81014_2"
                castShadow
                receiveShadow
                geometry={nodes.model_81014_2.geometry}
                material={materials.Tires}
              />
            </group>
            <group
              name="IM_Truck031"
              position={[2.37, 0.056, 1.914]}
              rotation={[-Math.PI, 0, 0]}
              scale={-0.021}
            >
              <mesh
                name="model_81014"
                castShadow
                receiveShadow
                geometry={nodes.model_81014.geometry}
                material={materials.backside}
              />
              <mesh
                name="model_81014_1"
                castShadow
                receiveShadow
                geometry={nodes.model_81014_1.geometry}
                material={materials.Body}
              />
              <mesh
                name="model_81014_2"
                castShadow
                receiveShadow
                geometry={nodes.model_81014_2.geometry}
                material={materials.Tires}
              />
            </group>
            <mesh
              name="M_L_TempStructures"
              castShadow
              receiveShadow
              geometry={nodes.M_L_TempStructures.geometry}
              material={materials.M_L_TempStructures}
              scale={0.024}
            />
            <mesh
              name="SM_CABIN_LP"
              castShadow
              receiveShadow
              geometry={nodes.SM_CABIN_LP.geometry}
              material={materials.M_Cabin_Master}
              scale={0.024}
            />
            <mesh
              name="SM_InnerEdgeSite"
              castShadow
              receiveShadow
              geometry={nodes.SM_InnerEdgeSite.geometry}
              material={materials.M_OuterSite}
              scale={0.024}
            />
            <mesh
              name="SM_L_CompoundWall"
              castShadow
              receiveShadow
              geometry={nodes.SM_L_CompoundWall.geometry}
              material={materials.M_L_Master_CompundWall}
              scale={0.024}
            />
            <group name="SM_L_CrashBarrier" scale={0.024}>
              <mesh
                name="Mesh001"
                castShadow
                receiveShadow
                geometry={nodes.Mesh001.geometry}
                material={materials.Crash_Barier_Poll}
              />
              <mesh
                name="Mesh001_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh001_1.geometry}
                material={materials.Crash_Barier}
              />
              <mesh
                name="Mesh001_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh001_2.geometry}
                material={materials.Crash_Bareier_Wall}
              />
            </group>
            <mesh
              name="SM_L_Curbs"
              castShadow
              receiveShadow
              geometry={nodes.SM_L_Curbs.geometry}
              material={materials.kurb}
              rotation={[0, Math.PI / 2, 0]}
              scale={0.024}
            />
            <mesh
              name="SM_L_Grasslawns"
              castShadow
              receiveShadow
              geometry={nodes.SM_L_Grasslawns.geometry}
              material={materials.M_L_Master_Site}
              rotation={[0, -1.571, 0]}
              scale={0.024}
            />
            <mesh
              name="SM_L_Internal_Roads"
              castShadow
              receiveShadow
              geometry={nodes.SM_L_Internal_Roads.geometry}
              material={materials.M_L_Master_Site}
              scale={0.024}
            />
            <group name="SM_L_MainGate" scale={0.024}>
              <mesh
                name="Mesh589"
                castShadow
                receiveShadow
                geometry={nodes.Mesh589.geometry}
                material={materials.M_COMPOUND_Wall}
              />
              <mesh
                name="Mesh589_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh589_1.geometry}
                material={materials.gate_texture}
              />
            </group>
            <mesh
              name="SM_L_ParkingSticker"
              castShadow
              receiveShadow
              geometry={nodes.SM_L_ParkingSticker.geometry}
              material={materials.parking}
              scale={0.024}
            />
            <mesh
              name="SM_L_Pond"
              castShadow
              receiveShadow
              geometry={nodes.SM_L_Pond.geometry}
              material={materials.WATER}
              scale={0.024}
            />
            <mesh
              name="SM_L_ROADLINES"
              castShadow
              receiveShadow
              geometry={nodes.SM_L_ROADLINES.geometry}
              material={materials["M_Road_Line.001"]}
              scale={0.024}
            />
            <mesh
              name="SM_L_Zebra_Crossing"
              castShadow
              receiveShadow
              geometry={nodes.SM_L_Zebra_Crossing.geometry}
              material={materials["M_Speed_Breaker.001"]}
              scale={0.024}
            />
            <group name="SM_Master_500" rotation={[0, 1.571, 0]} scale={0.024}>
              <mesh
                name="Plane529"
                castShadow
                receiveShadow
                geometry={nodes.Plane529.geometry}
                material={materials.M_Facade_Glass_Light}
              />
              <mesh
                name="Plane529_1"
                castShadow
                receiveShadow
                geometry={nodes.Plane529_1.geometry}
                material={materials["M_Master_B500.001"]}
              />
            </group>
            <group name="SM_Master_B100" scale={0.024}>
              <mesh
                name="Plane566"
                castShadow
                receiveShadow
                geometry={nodes.Plane566.geometry}
                material={materials.M_Master_B100}
              />
              <mesh
                name="Plane566_1"
                castShadow
                receiveShadow
                geometry={nodes.Plane566_1.geometry}
                material={materials.M_Facade_Glass_Light}
              />
            </group>
            <group
              name="SM_Master_B200"
              rotation={[Math.PI, 0, Math.PI]}
              scale={0.024}
            >
              <mesh
                name="Plane007"
                castShadow
                receiveShadow
                geometry={nodes.Plane007.geometry}
                material={materials.M_Facade_Glass_Light}
              />
              <mesh
                name="Plane007_1"
                castShadow
                receiveShadow
                geometry={nodes.Plane007_1.geometry}
                material={materials.M_Master_B200}
              />
            </group>
            <group
              name="SM_Master_B300"
              rotation={[Math.PI, 0, Math.PI]}
              scale={0.024}
            >
              <mesh
                name="Plane001"
                castShadow
                receiveShadow
                geometry={nodes.Plane001.geometry}
                material={materials["M_Master_B300.001"]}
              />
              <mesh
                name="Plane001_1"
                castShadow
                receiveShadow
                geometry={nodes.Plane001_1.geometry}
                material={materials["M_Master_B200.001"]}
              />
              <mesh
                name="Plane001_2"
                castShadow
                receiveShadow
                geometry={nodes.Plane001_2.geometry}
                material={materials["M_Facade_Glass_Light.001"]}
              />
            </group>
            <group name="SM_Master_B400" rotation={[0, 1.571, 0]} scale={0.024}>
              <mesh
                name="Plane533"
                castShadow
                receiveShadow
                geometry={nodes.Plane533.geometry}
                material={materials.M_Facade_Glass_Light}
              />
              <mesh
                name="Plane533_1"
                castShadow
                receiveShadow
                geometry={nodes.Plane533_1.geometry}
                material={materials.M_B_400}
              />
            </group>
            <mesh
              name="SM_OuterSite"
              castShadow
              receiveShadow
              geometry={nodes.SM_OuterSite.geometry}
              material={materials.M_OuterSite}
              scale={0.024}
            />
            <mesh
              name="SM_Service_Building"
              castShadow
              receiveShadow
              geometry={nodes.SM_Service_Building.geometry}
              material={materials.M_Small_Building_01}
              scale={0.024}
            />
            <mesh
              name="SM_Service_Building001"
              castShadow
              receiveShadow
              geometry={nodes.SM_Service_Building001.geometry}
              material={materials.M_Service_Building}
              scale={0.024}
            />

          </group>
          <PerspectiveCamera
            name="MainCameraAlt"
            ref={maincam1}
            makeDefault={true}
            far={1000}
            near={0.1}
            fov={22.895}
            position={[31.401, 13.534, 42.827]}
            rotation={[-0.32, 0.604, 0.186]}
          />
          <PerspectiveCamera
            name="Cam_B500"
            makeDefault={false}
            far={1000}
            near={0.1}
            fov={22.895}
            position={[-7.068, 5.436, 1.633]}
            rotation={[-0.595, -0.578, -0.354]}
          />
          <PerspectiveCamera
            name="Cam_B400"
            makeDefault={false}
            far={1000}
            near={0.1}
            fov={22.895}
            position={[-9.624, 3.417, -4.656]}
            rotation={[-2.567, -1.043, -2.632]}
          />
          <PerspectiveCamera
            name="Cam_B300"
            makeDefault={false}
            far={1000}
            near={0.1}
            fov={22.895}
            position={[-2.254, 4.107, -10.756]}
            rotation={[-2.787, 0.413, 2.994]}
          />
          <PerspectiveCamera
            name="Cam_B200"
            makeDefault={false}
            far={1000}
            near={0.1}
            fov={22.895}
            position={[6.601, 3.308, 15.383]}
            rotation={[-0.309, -0.625, -0.184]}
          />
          <PerspectiveCamera
            name="Cam_B100"
            makeDefault={false}
            ref={perspectiveCam}
            far={1000}
            near={0.1}
            fov={22.895}
            position={[12.437, 4.9, 16.587]}
            rotation={[-0.439, 0.715, 0.299]}
          />
        </group>
      </group>
    </>

  );
}

useGLTF.preload("/Test.glb");

