/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState } from "react";
import { useGLTF, PerspectiveCamera, useAnimations, OrbitControls } from "@react-three/drei";
import { useLoader, useFrame, useThree } from "@react-three/fiber";
import { TextureLoader } from "three";
import * as THREE from 'three'

let meshname = 'Default'

let isDragging = false;
let startX
let camTimeScale = 0
let lastXvalue = 0
let xdrag 
let isOpen = false;

const dropdownContent = document.getElementById('dropdown-content');
const sidebarImage = document.getElementById('sidebar');

document.getElementById('sidebar').addEventListener('click', (e) => {
  console.log(isOpen)
 isOpen = !isOpen;
  dropdownContent.style.display =isOpen ? 'block' : 'none';
  // Change the image source based on the dropdown state
  sidebarImage.src =isOpen ? './images/sidebarU.png' : './images/2024.01.29_SURF_PROJECT.NAME_WINDOW.CLOSED-41.png';
});

export function Model(props) {
  const modelRef1 = useRef();
  const modelRef2 = useRef();
  const modelRef3 = useRef();
  const modelRef4 = useRef();
  const modelRef5 = useRef();
  const modelRef6 = useRef();
  const modelRef7 = useRef();
  const modelRef8 = useRef();

  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/FinalModel.glb");
  const { actions, mixer } = useAnimations(animations, group);

  let img1 = './images/2024.01.29_ICON_HOTSPOT_BUTT.UNZOOM-43.png'
  let img2 = './images/B100.png'; // Change this to the path of your other texture
  let img3 = './images/B200.png'
  let img4 = "./images/B300.png"
  let img5 = "./images/B400.png"
  let img6 = "./images/B500.png"
  let view = "./images/2024.01.29_ICON_STREET.VIEW_BUTT-49.png"
  let howeverdview = "./images/360_BUTT.png"


  const [hovered1, setHovered1] = useState(false);
  const [hovered2, setHovered2] = useState(false);
  const [hovered3, setHovered3] = useState(false);
  const [hovered4, setHovered4] = useState(false);
  const [hovered5, setHovered5] = useState(false);
  const [hovered6, setHovered6] = useState(false);
  const [hovered7, setHovered7] = useState(false);
  const [hovered8, setHovered8] = useState(false);




  const hotspottex = useLoader(TextureLoader, img1);
  const hotspottexHovered = useLoader(TextureLoader, img2);
  const hotspottexHovered1 = useLoader(TextureLoader, img3);
  const hotspottexHovered2 = useLoader(TextureLoader, img4);
  const hotspottexHovered3 = useLoader(TextureLoader, img5);
  const hotspottexHovered4 = useLoader(TextureLoader, img6);
  const viewtex = useLoader(TextureLoader, view);
  const howeverdviewtex = useLoader(TextureLoader, howeverdview);

 useEffect(() => void (actions["MainCameraAltActionClip"].play().paused = true), [])
  //   const b100Camera = document.querySelector("#Cam_B100");
  // b100Camera.addEventListener("click", () => {
  //   animateToB100();
  // });

  // useEffect(() => {
  //   void(actions["MainCameraAltActionClip"]).play()
  //   mixer.timeScale = 0.5

  // },[]) 

  window.addEventListener('mousedown', startDrag);
  window.addEventListener('mousemove', drag);
  window.addEventListener('mouseup', stopDrag);

  function startDrag(e) {
    isDragging = true
    startX = e.clientX ;
    // startY = e.clientY;
    console.log("a", startX)

  }

  function drag(e) {
    xdrag = e.clientX - startX;
    xdrag = xdrag + lastXvalue
    // const y = e.clientY - startY;
    if (isDragging && xdrag > 10) {
      // console.log(x / 1000)
      camTimeScale = xdrag / 2000
    }
    else {
      // console.log("Not ")
    }
    if(xdrag >= 1000){
      xdrag = 0
    } 
    if(xdrag < 0){
      xdrag = 1000
    } 
  }

  function stopDrag(e) {
    lastXvalue = xdrag
    
    isDragging = false
  }

  let camPos = new THREE.Vector3()
  let camRot = new THREE.Vector3()

  const setCameraPosRot = (hotspotname) => {
    switch (hotspotname) {
      case 'B100':
        camPos.x = 12.437;
        camPos.y = 4.9;
        camPos.z = 16.587;
        camRot.x = -0.439;
        camRot.y = 0.715;
        camRot.z = 0.299;
        document.getElementById('bnmtitle').innerText = "Building name"
        document.getElementById('bname').innerText = "B100"
        document.getElementById('fareatitle').innerText = "Floor Area"
        document.getElementById('farea').innerText = "3,23,520 sq.ft. (30,056 sq.m.)"
        document.getElementById('mareatitle').innerText = "Mezzanine Area"
        document.getElementById('marea').innerText = "5,382 sq.ft (500 sq.m)"
        document.getElementById('totbareatitle').innerText = "Total Buid-up Area"
        document.getElementById('totbarea').innerText = " 3,28,902 sq.ft (30,556 sq.m.)"
        document.getElementById('Usage').innerText = "Clear Height"
        document.getElementById('Usage-P').innerText = "12 meters minimum"
        // document.getElementById('Usage').style.display = 'none'
        // document.getElementById('Usage-P').style.display = 'none'

        break;
      case 'B200':
        camPos.x = 6.601
        camPos.y = 3.308
        camPos.z = 15.383
        camRot.x = -0.309
        camRot.y = -0.625
        camRot.z = -0.184
        document.getElementById('bnmtitle').innerText = "Building name"
        document.getElementById('bname').innerText = "B200"
        document.getElementById('fareatitle').innerText = "Floor Area"
        document.getElementById('farea').innerText = "3,05,157 sq.ft. (28,350 sq.m.)"
        document.getElementById('mareatitle').innerText = "Mezzanine Area"
        document.getElementById('marea').innerText = " 5,382 sq.ft (500 sq.m)"
        document.getElementById('totbareatitle').innerText = "Total Buid-up Area"
        document.getElementById('totbarea').innerText = "3,10,539 sq.ft (28,850 sq.m.)"
        document.getElementById('Usage').innerText = "Clear Height"
        document.getElementById('Usage-P').innerText = "12 meters minimum"
        // document.getElementById('Usage').style.display = 'none'
        // document.getElementById('Usage-P').style.display = 'none'

        break;
      case 'B300':
        camPos.x = -2.254
        camPos.y = 4.107
        camPos.z = -10.756
        camRot.x = -2.787
        camRot.y = 0.413
        camRot.z = 2.994
        document.getElementById('bnmtitle').innerText = "Building name"
        document.getElementById('bname').innerText = "B300"
        document.getElementById('fareatitle').innerText = "Floor Area"
        document.getElementById('farea').innerText = "4,07,995 sq.ft. (37,904 sq.m.)"
        document.getElementById('mareatitle').innerText = "Mezzanine Area"
        document.getElementById('marea').innerText = "5,382 sq.ft (500 sq.m)"
        document.getElementById('totbareatitle').innerText = "Total Buid-up Area"
        document.getElementById('totbarea').innerText = "4,13,377 sq.ft (38,404 sq.m.)"
        document.getElementById('Usage').innerText = "Clear Height"
        document.getElementById('Usage-P').innerText = "12 meters minimum"
        // document.getElementById('Usage').style.display = 'none'
        // document.getElementById('Usage-P').style.display = 'none'

        break;
      case 'B400':
        camPos.x = -8.113
        camPos.y = 3.994
        camPos.z = -6.434
        camRot.x = -2.771
        camRot.y = -0.715
        camRot.z = -2.892
        document.getElementById('bnmtitle').innerText = "Building name"
        document.getElementById('bname').innerText = "B400"
        document.getElementById('fareatitle').innerText = "Floor Area"
        document.getElementById('farea').innerText = "2,60,982 sq.ft. (24,246 sq.m.)"
        document.getElementById('mareatitle').innerText = "Mezzanine Area"
        document.getElementById('marea').innerText = "5,382 sq.ft (500 sq.m)"
        document.getElementById('totbareatitle').innerText = "Total Buid-up Area"
        document.getElementById('totbarea').innerText = "2,66,363 sq.ft (24,746 sq.m.)"
        document.getElementById('Usage').innerText = "Clear Height"
        document.getElementById('Usage-P').innerText = "12 meters minimum"
        // document.getElementById('Usage').style.display = 'none'
        // document.getElementById('Usage-P').style.display = 'none'


        break;
      case 'B500':
        camPos.x = -7.068
        camPos.y = 5.436
        camPos.z = 1.633
        camRot.x = -0.595
        camRot.y = -0.578
        camRot.z = -0.354
        document.getElementById('bnmtitle').innerText = "Building name"
        document.getElementById('bname').innerText = "B500"
        document.getElementById('fareatitle').innerText = "Floor Area"
        document.getElementById('farea').innerText = "1,41,804 sq.ft. (13,174 sq.m.)"
        document.getElementById('mareatitle').innerText = "Mezzanine Area"
        document.getElementById('marea').innerText = "5,382 sq.ft (500 sq.m)"
        document.getElementById('totbareatitle').innerText = "Total Buid-up Area"
        document.getElementById('totbarea').innerText = "1,47,186 sq.ft (13,674 sq.m.)"
        document.getElementById('Usage').innerText = "Clear Height"
        document.getElementById('Usage-P').innerText = "12 meters minimum"
        // document.getElementById('Usage').style.display = 'none'
        // document.getElementById('Usage-P').style.display = 'none'

        


        break;
      case 'Default':
        camPos.x = 31.401
        camPos.y = 13.534
        camPos.z = 42.827
        camRot.x = -0.32
        camRot.y = 0.604
        camRot.z = 0.186

        document.getElementById('bnmtitle').innerHTML = "IndoSpace Industrial <br> Warehousing & Logistics Park"
        document.getElementById('bname').innerText = ""
        document.getElementById('fareatitle').innerText = "Total Land Parcel"
        document.getElementById('farea').innerText = "186 Acres"
        document.getElementById('mareatitle').innerText = "Plot 1 Land Area"
        document.getElementById('marea').innerText = "62 Acres"
        document.getElementById('totbareatitle').innerText = "Total Chargeable Area"
        document.getElementById('totbarea').innerHTML = "14,35,315 sq.ft. <br> (1,33,344 sq.m.)"
        // document.getElementById('clrhgttitle').innerText = "Type Of Land"
        // document.getElementById('clrhgt').innerText = "Industrial"
        document.getElementById('Usage').innerText = "Usage"
        document.getElementById('Usage-P').innerText = "Industrial, Warehousing & Logistics park"
        document.getElementById('Usage').style.display = 'block'
        document.getElementById('Usage-P').style.display = 'block'
      

        break;
      default:
        // console.log("Default Case")
    }
    document.getElementById('dropdown-content').style.display = 'block'
    document.getElementById('sidebar').src = './images/sidebarU.png'
    document.getElementById('bottombar').style.display='none'
   

    // isOpen = true;
  }

  const closeBtn = document.getElementById('cbtn')

  const perspectiveCam = useRef();
  const maincam1 = useRef()

  // let defaultCam = false

  // const { get, set } = useThree(({ get, set }) => ({ get, set }));

  const [clicked, setClicked] = useState(false)
  const [closed, setClose] = useState(false)

  closeBtn.addEventListener('click', () => {
    closeBtn.style.display = 'none'
    meshname = 'Default'
    setCameraPosRot(meshname)
    setClicked(false)
    setClose(true)
    document.getElementById('dropdown-content').style.display = 'none'
    document.getElementById('sidebar').src = './images/2024.01.29_SURF_PROJECT.NAME_WINDOW.CLOSED-41.png'
    document.getElementById('bottombar').style.display='block'

    // isOpen = false;
  })
 
  
  // useFrame(state => {
  //   if (clicked3) {
  //     state.camera.lookAt(-0.439, 0.715, 0.299)
  //     state.camera.position.set(12.437, 4.9, 16.587)
  //     state.camera.updateProjectionMatrix()
  //     closeBtn.style.display = 'block'
  //   }
  //   else if (!clicked3) {
  //     state.camera.lookAt(-0.32, 0.604, 0.186)
  //     state.camera.position.set(31.401, 13.534, 42.827)
  //     state.camera.updateProjectionMatrix()
  //   }
  //   return null
  // })

  useFrame(state => {
    console.log(meshname)
    if (clicked) {
      setCameraPosRot(meshname)
      state.camera.rotation.set(camRot.x, camRot.y, camRot.z)
      state.camera.position.set(camPos.x, camPos.y, camPos.z)
      state.camera.updateProjectionMatrix()
      closeBtn.style.display = 'block'
      if(isDragging){
        state.camera.rotation.y = camRot.y +  state.pointer.x /10
        // state.camera.rotation.z = camRot.z +  state.pointer.y /10
      }
      
    }
    else if (!clicked) {
      if (meshname == 'Default' && closed) {
        console.log('Close false')
        setClose(false)
        // state.camera.lookAt(-0.32, 0.604, 0.186)
        // state.camera.position.set(31.401, 13.534, 42.827)
        // state.camera.updateProjectionMatrix()

        // setTimeout(() => {
        //   setClose(false)

        // }, 3000);
      }
      else if (isDragging) {
       console.log(camTimeScale)

          actions["MainCameraAltActionClip"].time = THREE.MathUtils.lerp(actions["MainCameraAltActionClip"].time, actions["MainCameraAltActionClip"].getClip().duration * camTimeScale, 1)
        
      }else{
        camTimeScale += 0.00020
        if(camTimeScale >= 1){
          camTimeScale = 0
        } 
        if(camTimeScale < 0){
          camTimeScale = 1
        } 
          
      actions["MainCameraAltActionClip"].time = THREE.MathUtils.lerp(actions["MainCameraAltActionClip"].time, actions["MainCameraAltActionClip"].getClip().duration * camTimeScale, 1)
        modelRef1.current.lookAt(state.camera.position)
        modelRef2.current.lookAt(state.camera.position)
        modelRef3.current.lookAt(state.camera.position)
        modelRef4.current.lookAt(state.camera.position)
        modelRef5.current.lookAt(state.camera.position)
        modelRef6.current.lookAt(state.camera.position)
        modelRef7.current.lookAt(state.camera.position)
        modelRef8.current.lookAt(state.camera.position)
    }



    }
    return null
  })

  return (
    <>
      {/* b300 */}
      <mesh
        name="hotspotClick1"
        position={[-9.8, 2.75, 4.2]}
        rotation={[0, 0, 0]}
        ref={modelRef1}
        
        onClick={() => {
          meshname = 'B300'
          setClicked(true)
        }}
        
        onPointerOver={() => setHovered5(true)}
        onPointerOut={() => setHovered5(false)}
        scale={6}
      >
        <circleGeometry args={[0.07, 32]} />
        <meshBasicMaterial
          map={hovered5 ? hotspottexHovered2  : hotspottex}
          toneMapped={false}
          transparent={true}
          side={THREE.DoubleSide}
        />
      </mesh>
      {/* B100 */}
      <mesh

        position={[1.2, 2.9,8.4]}
        rotation={[0, 0, 0]}
        ref={modelRef2}
        onClick={() => {
          meshname = 'B100'
          setClicked(true)
        }}
        onPointerOver={() =>
          setHovered1(true)}
        onPointerOut={() =>
          setHovered1(false)}
        scale={6}

      >

        <circleGeometry args={[0.07, 32]} />
        <meshBasicMaterial
          map={hovered1 ? hotspottexHovered : hotspottex}
          toneMapped={false}
          transparent={true}
          side={THREE.DoubleSide}

        />

      </mesh>

      {/* B400 */}
      <mesh
        position={[1.6, 2.3, 1.5]}
        rotation={[0, 0, 0]}
        ref={modelRef3}
        onClick={() => {
          meshname = 'B400'
          setClicked(true)
        }}
        onPointerOver={() => setHovered4(true)}
        onPointerOut={() => setHovered4(false)}
        scale={6}
      >
        <circleGeometry args={[0.07, 32]} />
        <meshBasicMaterial
         map={hovered4 ? hotspottexHovered3 : hotspottex}
          toneMapped={false}
          transparent={true}
          side={THREE.DoubleSide}

        />
      </mesh>

      {/* B500 */}
      <mesh

        position={[2.1, 2.5, -5.5]}
        rotation={[0, 0, 0]}
        ref={modelRef4}
        onClick={() => {
          meshname = 'B500'
          setClicked(true)
        }}
        onPointerOver={() => setHovered3(true)}
        onPointerOut={() => setHovered3(false)}
       
        scale={6}
      >
        <circleGeometry args={[0.07, 32]} />
        <meshBasicMaterial
         map={hovered3 ? hotspottexHovered4 : hotspottex}

          toneMapped={false}
          transparent={true}
          side={THREE.DoubleSide}

        />
      </mesh>


      {/* B200 */}

      <mesh

        position={[14.6, 2.8,7]}
        rotation={[0, 0, 0]}
        ref={modelRef5}

        onClick={() => {
          meshname = 'B200'
          setClicked(true)
        }}
        onPointerOver={() => setHovered2(true)}
        onPointerOut={() => setHovered2(false)}
       
        scale={6}
      >
        <circleGeometry args={[0.07, 32]} />
        <meshBasicMaterial
          map={hovered2 ? hotspottexHovered1 : hotspottex}

          toneMapped={false}
          transparent={true}
          side={THREE.DoubleSide}

        />
      </mesh>
      {/* 360view 1*/}
      <mesh
        ref={modelRef6}
        position={[-4.7, 1.8, 12.5]}
        rotation={[0, 0, 0]}
        onPointerOver={() => setHovered6(true)}
        onPointerOut={() => setHovered6(false)}
        onClick={() => (
          console.log('Clicked 360 view'),
          document.getElementById('popupdarkbg').style.display = 'block',
          document.getElementById('popup').style.display = 'block',
          document.getElementById('popupiframe').src = 'https://equanimoustech.com/Indospace/VR1/',
          document.getElementById('dropdown-content').style.display = 'none',
          document.getElementById('sidebar').src = './images/2024.01.29_SURF_STREET.VIEW.01_WINDOW.OPEN-70.png'
        )}
        scale={6}
      >
        <circleGeometry args={[0.07, 32]} />
        <meshBasicMaterial
          map={hovered6 ? howeverdviewtex : viewtex}
          toneMapped={false}
          transparent={true}
          side={THREE.DoubleSide}

        />
      </mesh>


      {/* 360view 2*/}
      <mesh
        ref={modelRef7}
        position={[9.1, 1.8, 12.6]}
        rotation={[0, 0, 0]}
        onPointerOver={() => setHovered7(true)}
        onPointerOut={() => setHovered7(false)}
        onClick={() => (
          console.log('Clicked 360 view'),
          document.getElementById('popupdarkbg').style.display = 'block',
          document.getElementById('popup').style.display = 'block',
          document.getElementById('popupiframe').src = 'https://equanimoustech.com/Indospace/VR3/',
          document.getElementById('dropdown-content').style.display = 'none',
          document.getElementById('sidebar').src = './images/2024.01.29_SURF_STREET.VIEW.02_WINDOW.OPEN-71.png'
          

        )}
        
        scale={6}
      >
        <circleGeometry args={[0.07, 32]} />
        <meshBasicMaterial
          map={hovered7 ? howeverdviewtex : viewtex}
          toneMapped={false}
          transparent={true}
          side={THREE.DoubleSide}

        />
        
      </mesh>
      

      {/* 360view 3*/}
      <mesh
         ref={modelRef8}
        position={[0.9,1.7,-2]}
        rotation={[0, 0, 0]}
        onPointerOver={() => setHovered8(true)}
        onPointerOut={() => setHovered8(false)}
        onClick={() => (
          console.log('Clicked 360 view'),
          document.getElementById('popupdarkbg').style.display = 'block',
          document.getElementById('popup').style.display = 'block',
          document.getElementById('popupiframe').src = 'https://equanimoustech.com/Indospace/VR2/',
          document.getElementById('dropdown-content').style.display = 'none',
          document.getElementById('sidebar').src = './images/2024.01.29_SURF_STREET.VIEW.03_WINDOW.OPEN-72.png'
          
        )}
        scale={6}
      >
        <circleGeometry args={[0.07, 32]} />
        <meshBasicMaterial
          map={hovered8 ? howeverdviewtex : viewtex}
          toneMapped={false}
          transparent={true}
          side={THREE.DoubleSide}

        />
      </mesh>




      <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Chakan_V_Model" position={[0, 0.581, 0]} scale={2.169}>
          <group
            name="IM_Car_01010"
            position={[0.003, 0, 6.216]}
            rotation={[Math.PI, -1.571, 0]}
            scale={-0.024}
          >
            <mesh
              name="Mesh011"
              castShadow
              receiveShadow
              geometry={nodes.Mesh011.geometry}
              material={materials["74body.001"]}
            />
            <mesh
              name="Mesh011_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh011_1.geometry}
              material={materials["74basic.001"]}
            />
            <mesh
              name="Mesh011_2"
              castShadow
              receiveShadow
              geometry={nodes.Mesh011_2.geometry}
              material={materials["74FABRIC.001"]}
            />
            <mesh
              name="Mesh011_3"
              castShadow
              receiveShadow
              geometry={nodes.Mesh011_3.geometry}
              material={materials["74REK.001"]}
            />
            <mesh
              name="Mesh011_4"
              castShadow
              receiveShadow
              geometry={nodes.Mesh011_4.geometry}
              material={materials["74tyre.001"]}
            />
            <mesh
              name="Mesh011_5"
              castShadow
              receiveShadow
              geometry={nodes.Mesh011_5.geometry}
              material={materials["74tyresf.001"]}
            />
          </group>
          <group
            name="IM_Car_01011"
            position={[0, 0, 0.023]}
            rotation={[Math.PI, -1.571, 0]}
            scale={-0.024}
          >
            <mesh
              name="Mesh012"
              castShadow
              receiveShadow
              geometry={nodes.Mesh012.geometry}
              material={materials["73body.001"]}
            />
            <mesh
              name="Mesh012_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh012_1.geometry}
              material={materials["73basic.001"]}
            />
            <mesh
              name="Mesh012_2"
              castShadow
              receiveShadow
              geometry={nodes.Mesh012_2.geometry}
              material={materials["73fabric.001"]}
            />
            <mesh
              name="Mesh012_3"
              castShadow
              receiveShadow
              geometry={nodes.Mesh012_3.geometry}
              material={materials["73rek.001"]}
            />
            <mesh
              name="Mesh012_4"
              castShadow
              receiveShadow
              geometry={nodes.Mesh012_4.geometry}
              material={materials["73tyresf.003"]}
            />
            <mesh
              name="Mesh012_5"
              castShadow
              receiveShadow
              geometry={nodes.Mesh012_5.geometry}
              material={materials["73tyresf.004"]}
            />
            <mesh
              name="Mesh012_6"
              castShadow
              receiveShadow
              geometry={nodes.Mesh012_6.geometry}
              material={materials["73tyresf.005"]}
            />
          </group>
          <group
            name="IM_Car_01012"
            position={[0, -0.002, 0]}
            rotation={[0, 1.571, 0]}
            scale={0.024}
          >
            <mesh
              name="Mesh011"
              castShadow
              receiveShadow
              geometry={nodes.Mesh011.geometry}
              material={materials["74body.001"]}
            />
            <mesh
              name="Mesh011_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh011_1.geometry}
              material={materials["74basic.001"]}
            />
            <mesh
              name="Mesh011_2"
              castShadow
              receiveShadow
              geometry={nodes.Mesh011_2.geometry}
              material={materials["74FABRIC.001"]}
            />
            <mesh
              name="Mesh011_3"
              castShadow
              receiveShadow
              geometry={nodes.Mesh011_3.geometry}
              material={materials["74REK.001"]}
            />
            <mesh
              name="Mesh011_4"
              castShadow
              receiveShadow
              geometry={nodes.Mesh011_4.geometry}
              material={materials["74tyre.001"]}
            />
            <mesh
              name="Mesh011_5"
              castShadow
              receiveShadow
              geometry={nodes.Mesh011_5.geometry}
              material={materials["74tyresf.001"]}
            />
          </group>
          <group
            name="IM_Car_01036"
            position={[-0.209, -0.008, 0.496]}
            rotation={[0, 0, -Math.PI]}
            scale={-0.024}
          >
            <mesh
              name="Mesh019"
              castShadow
              receiveShadow
              geometry={nodes.Mesh019.geometry}
              material={materials["73body.001"]}
            />
            <mesh
              name="Mesh019_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh019_1.geometry}
              material={materials["73basic.001"]}
            />
            <mesh
              name="Mesh019_2"
              castShadow
              receiveShadow
              geometry={nodes.Mesh019_2.geometry}
              material={materials["73fabric.001"]}
            />
            <mesh
              name="Mesh019_3"
              castShadow
              receiveShadow
              geometry={nodes.Mesh019_3.geometry}
              material={materials["73rek.001"]}
            />
            <mesh
              name="Mesh019_4"
              castShadow
              receiveShadow
              geometry={nodes.Mesh019_4.geometry}
              material={materials["73tyresf.003"]}
            />
            <mesh
              name="Mesh019_5"
              castShadow
              receiveShadow
              geometry={nodes.Mesh019_5.geometry}
              material={materials["73tyresf.004"]}
            />
            <mesh
              name="Mesh019_6"
              castShadow
              receiveShadow
              geometry={nodes.Mesh019_6.geometry}
              material={materials["73tyresf.005"]}
            />
          </group>
          <group
            name="IM_Car_01039"
            position={[0.818, -0.007, 0.011]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={0.024}
          >
            <mesh
              name="Mesh018"
              castShadow
              receiveShadow
              geometry={nodes.Mesh018.geometry}
              material={materials["74body.001"]}
            />
            <mesh
              name="Mesh018_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh018_1.geometry}
              material={materials["74basic.001"]}
            />
            <mesh
              name="Mesh018_2"
              castShadow
              receiveShadow
              geometry={nodes.Mesh018_2.geometry}
              material={materials["74FABRIC.001"]}
            />
            <mesh
              name="Mesh018_3"
              castShadow
              receiveShadow
              geometry={nodes.Mesh018_3.geometry}
              material={materials["74REK.001"]}
            />
            <mesh
              name="Mesh018_4"
              castShadow
              receiveShadow
              geometry={nodes.Mesh018_4.geometry}
              material={materials["74tyre.001"]}
            />
            <mesh
              name="Mesh018_5"
              castShadow
              receiveShadow
              geometry={nodes.Mesh018_5.geometry}
              material={materials["74tyresf.001"]}
            />
          </group>
          <group
            name="IM_Car_01041"
            position={[-6.266, -0.002, 2.017]}
            rotation={[Math.PI, -1.571, 0]}
            scale={-0.024}
          >
            <mesh
              name="Mesh020"
              castShadow
              receiveShadow
              geometry={nodes.Mesh020.geometry}
              material={materials["74body.001"]}
            />
            <mesh
              name="Mesh020_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh020_1.geometry}
              material={materials["74basic.001"]}
            />
            <mesh
              name="Mesh020_2"
              castShadow
              receiveShadow
              geometry={nodes.Mesh020_2.geometry}
              material={materials["74FABRIC.001"]}
            />
            <mesh
              name="Mesh020_3"
              castShadow
              receiveShadow
              geometry={nodes.Mesh020_3.geometry}
              material={materials["74REK.001"]}
            />
            <mesh
              name="Mesh020_4"
              castShadow
              receiveShadow
              geometry={nodes.Mesh020_4.geometry}
              material={materials["74tyre.001"]}
            />
            <mesh
              name="Mesh020_5"
              castShadow
              receiveShadow
              geometry={nodes.Mesh020_5.geometry}
              material={materials["74tyresf.001"]}
            />
          </group>
          <group
            name="IM_Car_01042"
            position={[-6.201, -0.002, 2.017]}
            rotation={[Math.PI, -1.571, 0]}
            scale={-0.024}
          >
            <mesh
              name="Mesh021"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021.geometry}
              material={materials["73body.001"]}
            />
            <mesh
              name="Mesh021_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021_1.geometry}
              material={materials["73basic.001"]}
            />
            <mesh
              name="Mesh021_2"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021_2.geometry}
              material={materials["73fabric.001"]}
            />
            <mesh
              name="Mesh021_3"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021_3.geometry}
              material={materials["73rek.001"]}
            />
            <mesh
              name="Mesh021_4"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021_4.geometry}
              material={materials["73tyresf.003"]}
            />
            <mesh
              name="Mesh021_5"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021_5.geometry}
              material={materials["73tyresf.004"]}
            />
            <mesh
              name="Mesh021_6"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021_6.geometry}
              material={materials["73tyresf.005"]}
            />
          </group>
          <group
            name="IM_Car_01043"
            position={[-6.266, -0.004, 1.342]}
            rotation={[0, 1.571, 0]}
            scale={0.024}
          >
            <mesh
              name="Mesh020"
              castShadow
              receiveShadow
              geometry={nodes.Mesh020.geometry}
              material={materials["74body.001"]}
            />
            <mesh
              name="Mesh020_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh020_1.geometry}
              material={materials["74basic.001"]}
            />
            <mesh
              name="Mesh020_2"
              castShadow
              receiveShadow
              geometry={nodes.Mesh020_2.geometry}
              material={materials["74FABRIC.001"]}
            />
            <mesh
              name="Mesh020_3"
              castShadow
              receiveShadow
              geometry={nodes.Mesh020_3.geometry}
              material={materials["74REK.001"]}
            />
            <mesh
              name="Mesh020_4"
              castShadow
              receiveShadow
              geometry={nodes.Mesh020_4.geometry}
              material={materials["74tyre.001"]}
            />
            <mesh
              name="Mesh020_5"
              castShadow
              receiveShadow
              geometry={nodes.Mesh020_5.geometry}
              material={materials["74tyresf.001"]}
            />
          </group>
          <group
            name="IM_Car_01044"
            position={[-6.201, -0.004, 1.342]}
            rotation={[0, 1.571, 0]}
            scale={0.024}
          >
            <mesh
              name="Mesh021"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021.geometry}
              material={materials["73body.001"]}
            />
            <mesh
              name="Mesh021_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021_1.geometry}
              material={materials["73basic.001"]}
            />
            <mesh
              name="Mesh021_2"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021_2.geometry}
              material={materials["73fabric.001"]}
            />
            <mesh
              name="Mesh021_3"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021_3.geometry}
              material={materials["73rek.001"]}
            />
            <mesh
              name="Mesh021_4"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021_4.geometry}
              material={materials["73tyresf.003"]}
            />
            <mesh
              name="Mesh021_5"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021_5.geometry}
              material={materials["73tyresf.004"]}
            />
            <mesh
              name="Mesh021_6"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021_6.geometry}
              material={materials["73tyresf.005"]}
            />
          </group>
          <group
            name="IM_Car_01045"
            position={[-1.284, -0.002, 2.155]}
            rotation={[Math.PI, 0, 0]}
            scale={-0.024}
          >
            <mesh
              name="Mesh020"
              castShadow
              receiveShadow
              geometry={nodes.Mesh020.geometry}
              material={materials["74body.001"]}
            />
            <mesh
              name="Mesh020_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh020_1.geometry}
              material={materials["74basic.001"]}
            />
            <mesh
              name="Mesh020_2"
              castShadow
              receiveShadow
              geometry={nodes.Mesh020_2.geometry}
              material={materials["74FABRIC.001"]}
            />
            <mesh
              name="Mesh020_3"
              castShadow
              receiveShadow
              geometry={nodes.Mesh020_3.geometry}
              material={materials["74REK.001"]}
            />
            <mesh
              name="Mesh020_4"
              castShadow
              receiveShadow
              geometry={nodes.Mesh020_4.geometry}
              material={materials["74tyre.001"]}
            />
            <mesh
              name="Mesh020_5"
              castShadow
              receiveShadow
              geometry={nodes.Mesh020_5.geometry}
              material={materials["74tyresf.001"]}
            />
          </group>
          <group
            name="IM_Car_01046"
            position={[-1.284, -0.002, 2.155]}
            rotation={[Math.PI, 0, 0]}
            scale={-0.024}
          >
            <mesh
              name="Mesh021"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021.geometry}
              material={materials["73body.001"]}
            />
            <mesh
              name="Mesh021_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021_1.geometry}
              material={materials["73basic.001"]}
            />
            <mesh
              name="Mesh021_2"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021_2.geometry}
              material={materials["73fabric.001"]}
            />
            <mesh
              name="Mesh021_3"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021_3.geometry}
              material={materials["73rek.001"]}
            />
            <mesh
              name="Mesh021_4"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021_4.geometry}
              material={materials["73tyresf.003"]}
            />
            <mesh
              name="Mesh021_5"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021_5.geometry}
              material={materials["73tyresf.004"]}
            />
            <mesh
              name="Mesh021_6"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021_6.geometry}
              material={materials["73tyresf.005"]}
            />
          </group>
          <group name="IM_Car_01047" position={[2.279, 0, 2.137]} scale={0.024}>
            <mesh
              name="Mesh020"
              castShadow
              receiveShadow
              geometry={nodes.Mesh020.geometry}
              material={materials["74body.001"]}
            />
            <mesh
              name="Mesh020_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh020_1.geometry}
              material={materials["74basic.001"]}
            />
            <mesh
              name="Mesh020_2"
              castShadow
              receiveShadow
              geometry={nodes.Mesh020_2.geometry}
              material={materials["74FABRIC.001"]}
            />
            <mesh
              name="Mesh020_3"
              castShadow
              receiveShadow
              geometry={nodes.Mesh020_3.geometry}
              material={materials["74REK.001"]}
            />
            <mesh
              name="Mesh020_4"
              castShadow
              receiveShadow
              geometry={nodes.Mesh020_4.geometry}
              material={materials["74tyre.001"]}
            />
            <mesh
              name="Mesh020_5"
              castShadow
              receiveShadow
              geometry={nodes.Mesh020_5.geometry}
              material={materials["74tyresf.001"]}
            />
          </group>
          <group name="IM_Car_01048" position={[2.279, 0, 2.137]} scale={0.024}>
            <mesh
              name="Mesh021"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021.geometry}
              material={materials["73body.001"]}
            />
            <mesh
              name="Mesh021_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021_1.geometry}
              material={materials["73basic.001"]}
            />
            <mesh
              name="Mesh021_2"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021_2.geometry}
              material={materials["73fabric.001"]}
            />
            <mesh
              name="Mesh021_3"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021_3.geometry}
              material={materials["73rek.001"]}
            />
            <mesh
              name="Mesh021_4"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021_4.geometry}
              material={materials["73tyresf.003"]}
            />
            <mesh
              name="Mesh021_5"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021_5.geometry}
              material={materials["73tyresf.004"]}
            />
            <mesh
              name="Mesh021_6"
              castShadow
              receiveShadow
              geometry={nodes.Mesh021_6.geometry}
              material={materials["73tyresf.005"]}
            />
          </group>
          <group
            name="IM_Truck010"
            position={[2.704, 0.05, 1.914]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.019, -0.021, -0.021]}
          >
            <mesh
              name="model_81002"
              castShadow
              receiveShadow
              geometry={nodes.model_81002.geometry}
              material={materials["backside.001"]}
            />
            <mesh
              name="model_81002_1"
              castShadow
              receiveShadow
              geometry={nodes.model_81002_1.geometry}
              material={materials["Body.001"]}
            />
            <mesh
              name="model_81002_2"
              castShadow
              receiveShadow
              geometry={nodes.model_81002_2.geometry}
              material={materials["Tires.001"]}
            />
          </group>
          <group
            name="IM_Truck011"
            position={[2.704, 0.05, 2.57]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.019, -0.021, -0.021]}
          >
            <mesh
              name="model_81002"
              castShadow
              receiveShadow
              geometry={nodes.model_81002.geometry}
              material={materials["backside.001"]}
            />
            <mesh
              name="model_81002_1"
              castShadow
              receiveShadow
              geometry={nodes.model_81002_1.geometry}
              material={materials["Body.001"]}
            />
            <mesh
              name="model_81002_2"
              castShadow
              receiveShadow
              geometry={nodes.model_81002_2.geometry}
              material={materials["Tires.001"]}
            />
          </group>
          <group
            name="IM_Truck012"
            position={[2.704, 0.05, 3.238]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.019, -0.021, -0.021]}
          >
            <mesh
              name="model_81002"
              castShadow
              receiveShadow
              geometry={nodes.model_81002.geometry}
              material={materials["backside.001"]}
            />
            <mesh
              name="model_81002_1"
              castShadow
              receiveShadow
              geometry={nodes.model_81002_1.geometry}
              material={materials["Body.001"]}
            />
            <mesh
              name="model_81002_2"
              castShadow
              receiveShadow
              geometry={nodes.model_81002_2.geometry}
              material={materials["Tires.001"]}
            />
          </group>
          <group
            name="IM_Truck013"
            position={[2.704, 0.05, 3.995]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.019, -0.021, -0.021]}
          >
            <mesh
              name="model_81002"
              castShadow
              receiveShadow
              geometry={nodes.model_81002.geometry}
              material={materials["backside.001"]}
            />
            <mesh
              name="model_81002_1"
              castShadow
              receiveShadow
              geometry={nodes.model_81002_1.geometry}
              material={materials["Body.001"]}
            />
            <mesh
              name="model_81002_2"
              castShadow
              receiveShadow
              geometry={nodes.model_81002_2.geometry}
              material={materials["Tires.001"]}
            />
          </group>
          <group
            name="IM_Truck026"
            position={[2.704, 0.05, 4.371]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.019, -0.021, -0.021]}
          >
            <mesh
              name="model_81002"
              castShadow
              receiveShadow
              geometry={nodes.model_81002.geometry}
              material={materials["backside.001"]}
            />
            <mesh
              name="model_81002_1"
              castShadow
              receiveShadow
              geometry={nodes.model_81002_1.geometry}
              material={materials["Body.001"]}
            />
            <mesh
              name="model_81002_2"
              castShadow
              receiveShadow
              geometry={nodes.model_81002_2.geometry}
              material={materials["Tires.001"]}
            />
          </group>
          <group name="IM_Truck028" position={[0.635, -0.004, 0]} scale={0.024}>
            <mesh
              name="model_81003"
              castShadow
              receiveShadow
              geometry={nodes.model_81003.geometry}
              material={materials["backside.001"]}
            />
            <mesh
              name="model_81003_1"
              castShadow
              receiveShadow
              geometry={nodes.model_81003_1.geometry}
              material={materials["Body.001"]}
            />
            <mesh
              name="model_81003_2"
              castShadow
              receiveShadow
              geometry={nodes.model_81003_2.geometry}
              material={materials["Tires.001"]}
            />
          </group>
          <group name="IM_Truck030" position={[0.365, -0.004, 0]} scale={0.024}>
            <mesh
              name="model_81003"
              castShadow
              receiveShadow
              geometry={nodes.model_81003.geometry}
              material={materials["backside.001"]}
            />
            <mesh
              name="model_81003_1"
              castShadow
              receiveShadow
              geometry={nodes.model_81003_1.geometry}
              material={materials["Body.001"]}
            />
            <mesh
              name="model_81003_2"
              castShadow
              receiveShadow
              geometry={nodes.model_81003_2.geometry}
              material={materials["Tires.001"]}
            />
          </group>
          <group name="IM_Truck032" position={[0, -0.004, 0]} scale={0.024}>
            <mesh
              name="model_81003"
              castShadow
              receiveShadow
              geometry={nodes.model_81003.geometry}
              material={materials["backside.001"]}
            />
            <mesh
              name="model_81003_1"
              castShadow
              receiveShadow
              geometry={nodes.model_81003_1.geometry}
              material={materials["Body.001"]}
            />
            <mesh
              name="model_81003_2"
              castShadow
              receiveShadow
              geometry={nodes.model_81003_2.geometry}
              material={materials["Tires.001"]}
            />
          </group>
          <group name="IM_Truck033" position={[0.646, -0.004, 0]} scale={0.024}>
            <mesh
              name="model_81004"
              castShadow
              receiveShadow
              geometry={nodes.model_81004.geometry}
              material={materials["backside.001"]}
            />
            <mesh
              name="model_81004_1"
              castShadow
              receiveShadow
              geometry={nodes.model_81004_1.geometry}
              material={materials["Body.001"]}
            />
            <mesh
              name="model_81004_2"
              castShadow
              receiveShadow
              geometry={nodes.model_81004_2.geometry}
              material={materials["Tires.001"]}
            />
          </group>
          <group name="IM_Truck034" position={[0.369, -0.004, 0]} scale={0.024}>
            <mesh
              name="model_81004"
              castShadow
              receiveShadow
              geometry={nodes.model_81004.geometry}
              material={materials["backside.001"]}
            />
            <mesh
              name="model_81004_1"
              castShadow
              receiveShadow
              geometry={nodes.model_81004_1.geometry}
              material={materials["Body.001"]}
            />
            <mesh
              name="model_81004_2"
              castShadow
              receiveShadow
              geometry={nodes.model_81004_2.geometry}
              material={materials["Tires.001"]}
            />
          </group>
          <group name="IM_Truck035" position={[0, -0.004, 0]} scale={0.024}>
            <mesh
              name="model_81004"
              castShadow
              receiveShadow
              geometry={nodes.model_81004.geometry}
              material={materials["backside.001"]}
            />
            <mesh
              name="model_81004_1"
              castShadow
              receiveShadow
              geometry={nodes.model_81004_1.geometry}
              material={materials["Body.001"]}
            />
            <mesh
              name="model_81004_2"
              castShadow
              receiveShadow
              geometry={nodes.model_81004_2.geometry}
              material={materials["Tires.001"]}
            />
          </group>
          <group
            name="IM_Truck036"
            position={[-0.447, 0, -1.134]}
            scale={[0.02, 0.024, 0.024]}
          >
            <mesh
              name="model_81002"
              castShadow
              receiveShadow
              geometry={nodes.model_81002.geometry}
              material={materials["backside.001"]}
            />
            <mesh
              name="model_81002_1"
              castShadow
              receiveShadow
              geometry={nodes.model_81002_1.geometry}
              material={materials["Body.001"]}
            />
            <mesh
              name="model_81002_2"
              castShadow
              receiveShadow
              geometry={nodes.model_81002_2.geometry}
              material={materials["Tires.001"]}
            />
          </group>
          <group
            name="IM_Truck037"
            position={[-0.447, 0, -0.754]}
            scale={[0.02, 0.024, 0.024]}
          >
            <mesh
              name="model_81002"
              castShadow
              receiveShadow
              geometry={nodes.model_81002.geometry}
              material={materials["backside.001"]}
            />
            <mesh
              name="model_81002_1"
              castShadow
              receiveShadow
              geometry={nodes.model_81002_1.geometry}
              material={materials["Body.001"]}
            />
            <mesh
              name="model_81002_2"
              castShadow
              receiveShadow
              geometry={nodes.model_81002_2.geometry}
              material={materials["Tires.001"]}
            />
          </group>
          <group
            name="IM_Truck038"
            position={[-0.447, 0, -0.381]}
            scale={[0.02, 0.024, 0.024]}
          >
            <mesh
              name="model_81002"
              castShadow
              receiveShadow
              geometry={nodes.model_81002.geometry}
              material={materials["backside.001"]}
            />
            <mesh
              name="model_81002_1"
              castShadow
              receiveShadow
              geometry={nodes.model_81002_1.geometry}
              material={materials["Body.001"]}
            />
            <mesh
              name="model_81002_2"
              castShadow
              receiveShadow
              geometry={nodes.model_81002_2.geometry}
              material={materials["Tires.001"]}
            />
          </group>
          <group
            name="IM_Truck039"
            position={[-0.447, 0, 0]}
            scale={[0.02, 0.024, 0.024]}
          >
            <mesh
              name="model_81002"
              castShadow
              receiveShadow
              geometry={nodes.model_81002.geometry}
              material={materials["backside.001"]}
            />
            <mesh
              name="model_81002_1"
              castShadow
              receiveShadow
              geometry={nodes.model_81002_1.geometry}
              material={materials["Body.001"]}
            />
            <mesh
              name="model_81002_2"
              castShadow
              receiveShadow
              geometry={nodes.model_81002_2.geometry}
              material={materials["Tires.001"]}
            />
          </group>
          <group name="IM_Truck040" position={[0.3, 0, 0]} scale={0.024}>
            <mesh
              name="model_81006"
              castShadow
              receiveShadow
              geometry={nodes.model_81006.geometry}
              material={materials["backside.001"]}
            />
            <mesh
              name="model_81006_1"
              castShadow
              receiveShadow
              geometry={nodes.model_81006_1.geometry}
              material={materials["Body.001"]}
            />
            <mesh
              name="model_81006_2"
              castShadow
              receiveShadow
              geometry={nodes.model_81006_2.geometry}
              material={materials["Tires.001"]}
            />
          </group>
          <group name="IM_Truck041" position={[-0.642, 0, 0]} scale={0.024}>
            <mesh
              name="model_81006"
              castShadow
              receiveShadow
              geometry={nodes.model_81006.geometry}
              material={materials["backside.001"]}
            />
            <mesh
              name="model_81006_1"
              castShadow
              receiveShadow
              geometry={nodes.model_81006_1.geometry}
              material={materials["Body.001"]}
            />
            <mesh
              name="model_81006_2"
              castShadow
              receiveShadow
              geometry={nodes.model_81006_2.geometry}
              material={materials["Tires.001"]}
            />
          </group>
          <group name="IM_Truck042" position={[-0.269, 0, 0]} scale={0.024}>
            <mesh
              name="model_81006"
              castShadow
              receiveShadow
              geometry={nodes.model_81006.geometry}
              material={materials["backside.001"]}
            />
            <mesh
              name="model_81006_1"
              castShadow
              receiveShadow
              geometry={nodes.model_81006_1.geometry}
              material={materials["Body.001"]}
            />
            <mesh
              name="model_81006_2"
              castShadow
              receiveShadow
              geometry={nodes.model_81006_2.geometry}
              material={materials["Tires.001"]}
            />
          </group>
          <group name="IM_Truck043" scale={0.024}>
            <mesh
              name="model_81006"
              castShadow
              receiveShadow
              geometry={nodes.model_81006.geometry}
              material={materials["backside.001"]}
            />
            <mesh
              name="model_81006_1"
              castShadow
              receiveShadow
              geometry={nodes.model_81006_1.geometry}
              material={materials["Body.001"]}
            />
            <mesh
              name="model_81006_2"
              castShadow
              receiveShadow
              geometry={nodes.model_81006_2.geometry}
              material={materials["Tires.001"]}
            />
          </group>
          <group name="IM_Truck045" position={[-0.847, 0, 0]} scale={0.024}>
            <mesh
              name="model_81007"
              castShadow
              receiveShadow
              geometry={nodes.model_81007.geometry}
              material={materials["backside.001"]}
            />
            <mesh
              name="model_81007_1"
              castShadow
              receiveShadow
              geometry={nodes.model_81007_1.geometry}
              material={materials["Body.001"]}
            />
            <mesh
              name="model_81007_2"
              castShadow
              receiveShadow
              geometry={nodes.model_81007_2.geometry}
              material={materials["Tires.001"]}
            />
          </group>
          <group name="IM_Truck046" position={[-0.568, 0, 0]} scale={0.024}>
            <mesh
              name="model_81007"
              castShadow
              receiveShadow
              geometry={nodes.model_81007.geometry}
              material={materials["backside.001"]}
            />
            <mesh
              name="model_81007_1"
              castShadow
              receiveShadow
              geometry={nodes.model_81007_1.geometry}
              material={materials["Body.001"]}
            />
            <mesh
              name="model_81007_2"
              castShadow
              receiveShadow
              geometry={nodes.model_81007_2.geometry}
              material={materials["Tires.001"]}
            />
          </group>
          <group name="IM_Truck047" position={[-0.286, 0, 0]} scale={0.024}>
            <mesh
              name="model_81007"
              castShadow
              receiveShadow
              geometry={nodes.model_81007.geometry}
              material={materials["backside.001"]}
            />
            <mesh
              name="model_81007_1"
              castShadow
              receiveShadow
              geometry={nodes.model_81007_1.geometry}
              material={materials["Body.001"]}
            />
            <mesh
              name="model_81007_2"
              castShadow
              receiveShadow
              geometry={nodes.model_81007_2.geometry}
              material={materials["Tires.001"]}
            />
          </group>
          <group name="IM_Truck048" scale={0.024}>
            <mesh
              name="model_81007"
              castShadow
              receiveShadow
              geometry={nodes.model_81007.geometry}
              material={materials["backside.001"]}
            />
            <mesh
              name="model_81007_1"
              castShadow
              receiveShadow
              geometry={nodes.model_81007_1.geometry}
              material={materials["Body.001"]}
            />
            <mesh
              name="model_81007_2"
              castShadow
              receiveShadow
              geometry={nodes.model_81007_2.geometry}
              material={materials["Tires.001"]}
            />
          </group>
        </group>
        <mesh
          name="Plane"
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials.M_L_Master_CompundWall}
          position={[7.623, 1.769, 13.997]}
          rotation={[0, -1.206, -Math.PI / 2]}
          scale={[0.615, 1.555, 1.555]}
        />
        <group name="Empty" position={[0, 1.721, 0]} scale={0.498}>
          <mesh
            name="0_curve_001"
            castShadow
            receiveShadow
            geometry={nodes["0_curve_001"].geometry}
            material={materials.Crash_Barier_Poll}
            position={[7.238, -1.152, -2.193]}
            scale={0.102}
          />
          <mesh
            name="M_L_TempStructures"
            castShadow
            receiveShadow
            geometry={nodes.M_L_TempStructures.geometry}
            material={materials.M_L_TempStructures}
            position={[18.221, 0.632, 22.373]}
            scale={0.102}
          />
          <group
            name="New_Building"
            position={[-24.163, -0.138, 25.958]}
            scale={1.315}
          />
          <group
            name="New_Building001"
            position={[-24.163, -0.138, 25.958]}
            scale={1.315}
          />
          <group
            name="New_Building002"
            position={[-24.163, -0.138, 25.958]}
            scale={1.315}
          />
          <mesh
            name="SM_CABIN_LP"
            castShadow
            receiveShadow
            geometry={nodes.SM_CABIN_LP.geometry}
            material={materials.M_Cabin_Master}
            position={[18.502, -0.138, 26.839]}
            scale={0.102}
          />
          <mesh
            name="SM_InnerEdgeSite"
            castShadow
            receiveShadow
            geometry={nodes.SM_InnerEdgeSite.geometry}
            material={materials.M_OuterSite_01}
            position={[1.241, -0.264, -9.02]}
            scale={0.102}
          />
          <mesh
            name="SM_L_CompoundWall"
            castShadow
            receiveShadow
            geometry={nodes.SM_L_CompoundWall.geometry}
            material={materials.M_L_Master_CompundWall}
            position={[14.633, -0.143, 28.344]}
            scale={0.102}
          />
          <mesh
            name="SM_L_Grasslawns"
            castShadow
            receiveShadow
            geometry={nodes.SM_L_Grasslawns.geometry}
            material={materials.M_Site}
            position={[-13.419, -0.128, -7.648]}
            rotation={[0, -1.571, 0]}
            scale={0.102}
          />
          <mesh
            name="SM_L_Internal_Roads"
            castShadow
            receiveShadow
            geometry={nodes.SM_L_Internal_Roads.geometry}
            material={materials.M_Site}
            position={[6.011, -0.696, 5.553]}
            scale={0.102}
          />
          <group
            name="SM_L_MainGate"
            position={[18.592, -0.038, 27.472]}
            scale={0.102}
          >
            <mesh
              name="Mesh589"
              castShadow
              receiveShadow
              geometry={nodes.Mesh589.geometry}
              material={materials.M_COMPOUND_Wall}
            />
            <mesh
              name="Mesh589_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh589_1.geometry}
              material={materials.gate_texture}
            />
          </group>
          <mesh
            name="SM_L_Pond"
            castShadow
            receiveShadow
            geometry={nodes.SM_L_Pond.geometry}
            material={materials.WATER}
            position={[-21.116, -1.233, -19.029]}
            scale={0.102}
          />
          <mesh
            name="SM_L_Zebra_Crossing"
            castShadow
            receiveShadow
            geometry={nodes.SM_L_Zebra_Crossing.geometry}
            material={materials.M_Speed_Breaker}
            position={[-8.799, -0.138, 25.533]}
            scale={0.102}
          />
          <group
            name="SM_Master_500"
            position={[-6.865, -1.161, -7.676]}
            rotation={[0, 1.571, 0]}
            scale={0.102}
          >
            <mesh
              name="Plane529"
              castShadow
              receiveShadow
              geometry={nodes.Plane529.geometry}
              material={materials.M_Facade_Glass_Light}
            />
            <mesh
              name="Plane529_1"
              castShadow
              receiveShadow
              geometry={nodes.Plane529_1.geometry}
              material={materials.M_Master_B500}
            />
            <mesh
              name="Plane529_2"
              castShadow
              receiveShadow
              geometry={nodes.Plane529_2.geometry}
              material={materials.M_B_400}
            />
          </group>
          <group
            name="SM_Master_B100001"
            position={[-10.396, -0.036, 22.686]}
            scale={0.102}
          >
            <mesh
              name="Plane004"
              castShadow
              receiveShadow
              geometry={nodes.Plane004.geometry}
              material={materials.M_Master_B100}
            />
            <mesh
              name="Plane004_1"
              castShadow
              receiveShadow
              geometry={nodes.Plane004_1.geometry}
              material={materials.M_Facade_Glass_Light}
            />
            <mesh
              name="Plane004_2"
              castShadow
              receiveShadow
              geometry={nodes.Plane004_2.geometry}
              material={materials.M_B_400}
            />
          </group>
          <mesh
            name="SM_Master_B100009"
            castShadow
            receiveShadow
            geometry={nodes.SM_Master_B100009.geometry}
            material={materials.M_B_400}
            position={[-13.91, 1.079, 12.226]}
            rotation={[-Math.PI, -1.571, 0]}
            scale={-0.102}
          />
          <group
            name="SM_Master_B200"
            position={[36.211, -0.044, 24.28]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={0.102}
          >
            <mesh
              name="Plane007"
              castShadow
              receiveShadow
              geometry={nodes.Plane007.geometry}
              material={materials.M_Facade_Glass_Light}
            />
            <mesh
              name="Plane007_1"
              castShadow
              receiveShadow
              geometry={nodes.Plane007_1.geometry}
              material={materials.M_Master_B200}
            />
            <mesh
              name="Plane007_2"
              castShadow
              receiveShadow
              geometry={nodes.Plane007_2.geometry}
              material={materials.M_B_400}
            />
          </group>
          <group
            name="SM_Master_B300"
            position={[-13.605, -0.036, 25.958]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={0.102}
          >
            <mesh
              name="Plane001"
              castShadow
              receiveShadow
              geometry={nodes.Plane001.geometry}
              material={materials.M_Master_B300}
            />
            <mesh
              name="Plane001_1"
              castShadow
              receiveShadow
              geometry={nodes.Plane001_1.geometry}
              material={materials.M_Master_B200}
            />
            <mesh
              name="Plane001_2"
              castShadow
              receiveShadow
              geometry={nodes.Plane001_2.geometry}
              material={materials.M_Facade_Glass_Light}
            />
            <mesh
              name="Plane001_3"
              castShadow
              receiveShadow
              geometry={nodes.Plane001_3.geometry}
              material={materials.M_B_400}
            />
          </group>
          <group
            name="SM_Master_B400"
            position={[-8.171, -1.165, 7.547]}
            rotation={[0, 1.571, 0]}
            scale={0.102}
          >
            <mesh
              name="Plane533"
              castShadow
              receiveShadow
              geometry={nodes.Plane533.geometry}
              material={materials.M_Facade_Glass_Light}
            />
            <mesh
              name="Plane533_1"
              castShadow
              receiveShadow
              geometry={nodes.Plane533_1.geometry}
              material={materials.M_B_400}
            />
          </group>
          <mesh
            name="SM_OG_ROAD012"
            castShadow
            receiveShadow
            geometry={nodes.SM_OG_ROAD012.geometry}
            material={materials.M_Kurb}
            position={[22.232, -0.124, 6.438]}
            rotation={[0, Math.PI / 2, 0]}
            scale={0.102}
          />
          <mesh
            name="SM_OuterSite"
            castShadow
            receiveShadow
            geometry={nodes.SM_OuterSite.geometry}
            material={materials.M_OuterSite}
            scale={0.102}
          />
          <group
            name="SM_ROAD002"
            position={[-2.355, -0.64, -2.186]}
            scale={0.102}
          >
            <mesh
              name="SM_ROAD004"
              castShadow
              receiveShadow
              geometry={nodes.SM_ROAD004.geometry}
              material={materials.Crash_Barier}
            />
            <mesh
              name="SM_ROAD004_1"
              castShadow
              receiveShadow
              geometry={nodes.SM_ROAD004_1.geometry}
              material={materials.Crash_Bareier_Wall}
            />
          </group>
          <mesh
            name="SM_ROAD050"
            castShadow
            receiveShadow
            geometry={nodes.SM_ROAD050.geometry}
            material={materials.M_Road_Line}
            position={[18.221, -0.137, 22.373]}
            scale={0.102}
          />
          <mesh
            name="SM_Service_Building"
            castShadow
            receiveShadow
            geometry={nodes.SM_Service_Building.geometry}
            material={materials.M_Small_Building_01}
            position={[15.039, -0.123, 25.908]}
            scale={0.102}
          />
          <mesh
            name="SM_Service_Building001"
            castShadow
            receiveShadow
            geometry={nodes.SM_Service_Building001.geometry}
            material={materials.M_Service_Building}
            position={[15.039, -0.123, 25.908]}
            scale={0.102}
          />
        </group>
        <PerspectiveCamera
          name="MainCameraAlt"
          makeDefault={true}
          far={1000}
          near={0.1}
          fov={22.895}
          position={[31.401, 13.534, 42.827]}
          rotation={[-0.32, 0.604, 0.186]}
        />
        <PerspectiveCamera
          name="Cam_B500"
          makeDefault={false}
          far={1000}
          near={0.1}
          fov={22.895}
          position={[-4.867, 5.936, 2.598]}
          rotation={[-0.508, -0.264, -0.144]}
        />
        <PerspectiveCamera
          name="Cam_B400"
          makeDefault={false}
          far={1000}
          near={0.1}
          fov={22.895}
          position={[-8.113, 3.994, -6.434]}
          rotation={[-2.771, -0.715, -2.892]}
        />
        <PerspectiveCamera
          name="Cam_B300"
          makeDefault={false}
          far={1000}
          near={0.1}
          fov={22.895}
          position={[-0.207, 4.597, -8.699]}
          rotation={[-2.691, 0.751, 2.823]}
        />
        <PerspectiveCamera
          name="Cam_B200"
          makeDefault={false}
          far={1000}
          near={0.1}
          fov={22.895}
          position={[5.421, 3.904, 13.476]}
          rotation={[-0.449, -0.966, -0.377]}
        />
        <PerspectiveCamera
          name="Cam_B100"
          makeDefault={false}
          far={1000}
          near={0.1}
          fov={22.895}
          position={[10.187, 5.448, 18.031]}
          rotation={[-0.353, 0.376, 0.134]}
        />
        <group name="Empty002" position={[0, 1.593, 0]} scale={2.126}>
          <group
            name="IM_Lamp042"
            position={[4.677, -0.028, 6.354]}
            rotation={[-Math.PI, 0, 0]}
            scale={-0.012}
          >
            <mesh
              name="Cylinder001"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder001.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder001_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder001_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp043"
            position={[4.388, -0.031, 4.452]}
            rotation={[-Math.PI, Math.PI / 4, 0]}
            scale={-0.012}
          >
            <mesh
              name="Cylinder003"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder003.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder003_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder003_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp044"
            position={[3.833, -0.289, 1.551]}
            scale={0.012}
          >
            <mesh
              name="Cylinder004"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder004.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder004_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder004_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp045"
            position={[3.767, -0.029, 6.352]}
            scale={0.012}
          >
            <mesh
              name="Cylinder005"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder005.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder005_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder005_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp046"
            position={[3.537, -0.029, 5.196]}
            scale={0.012}
          >
            <mesh
              name="Cylinder005"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder005.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder005_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder005_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp047"
            position={[3.538, -0.029, 4.064]}
            scale={0.012}
          >
            <mesh
              name="Cylinder005"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder005.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder005_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder005_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp048"
            position={[8.514, -0.029, 4.381]}
            scale={0.012}
          >
            <mesh
              name="Cylinder005"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder005.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder005_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder005_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp049"
            position={[8.514, -0.029, 3.315]}
            scale={0.012}
          >
            <mesh
              name="Cylinder005"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder005.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder005_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder005_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp050"
            position={[8.514, -0.029, 1.91]}
            scale={0.012}
          >
            <mesh
              name="Cylinder005"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder005.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder005_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder005_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp051"
            position={[8.529, -0.028, 0.846]}
            scale={0.012}
          >
            <mesh
              name="Cylinder005"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder005.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder005_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder005_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp052"
            position={[3.551, -0.028, 2.932]}
            scale={0.012}
          >
            <mesh
              name="Cylinder005"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder005.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder005_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder005_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp053"
            position={[4.539, -0.025, 2.094]}
            scale={0.012}
          >
            <mesh
              name="Cylinder005"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder005.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder005_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder005_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp054"
            position={[4.539, -0.025, 1.319]}
            scale={0.012}
          >
            <mesh
              name="Cylinder005"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder005.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder005_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder005_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp055"
            position={[3.833, -0.289, 0.813]}
            scale={0.012}
          >
            <mesh
              name="Cylinder004"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder004.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder004_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder004_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp056"
            position={[2.625, -0.289, -3.385]}
            scale={0.012}
          >
            <mesh
              name="Cylinder007"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder007.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder007_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder007_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp057"
            position={[3.85, -0.288, 0.075]}
            scale={0.012}
          >
            <mesh
              name="Cylinder004"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder004.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder004_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder004_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp058"
            position={[2.625, -0.289, -1.989]}
            scale={0.012}
          >
            <mesh
              name="Cylinder007"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder007.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder007_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder007_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp059"
            position={[2.625, -0.289, -2.763]}
            scale={0.012}
          >
            <mesh
              name="Cylinder007"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder007.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder007_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder007_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp060"
            position={[-0.411, -0.271, -4.178]}
            rotation={[0, -1.571, 0]}
            scale={0.012}
          >
            <mesh
              name="Cylinder008"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder008.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder008_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder008_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp061"
            position={[2.525, -0.219, -4.178]}
            rotation={[0, -1.571, 0]}
            scale={0.012}
          >
            <mesh
              name="Cylinder008"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder008.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder008_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder008_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp062"
            position={[0.834, -0.228, -4.178]}
            rotation={[0, -1.571, 0]}
            scale={0.012}
          >
            <mesh
              name="Cylinder008"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder008.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder008_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder008_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp063"
            position={[0.249, -0.25, -4.178]}
            rotation={[0, -1.571, 0]}
            scale={0.012}
          >
            <mesh
              name="Cylinder008"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder008.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder008_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder008_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp064"
            position={[-3.479, -0.032, -2.8]}
            rotation={[0, 1.571, 0]}
            scale={0.012}
          >
            <mesh
              name="Cylinder009"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder009.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder009_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder009_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp065"
            position={[-5.539, -0.032, -2.8]}
            rotation={[0, 1.571, 0]}
            scale={0.012}
          >
            <mesh
              name="Cylinder009"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder009.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder009_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder009_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp066"
            position={[-4.522, -0.032, -2.8]}
            rotation={[0, 1.571, 0]}
            scale={0.012}
          >
            <mesh
              name="Cylinder009"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder009.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder009_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder009_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp067"
            position={[-2.481, -0.032, 5.039]}
            rotation={[-Math.PI, 0, 0]}
            scale={-0.012}
          >
            <mesh
              name="Cylinder010"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder010.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder010_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder010_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp068"
            position={[-1.76, -0.289, -3.283]}
            rotation={[-Math.PI, 0, 0]}
            scale={-0.012}
          >
            <mesh
              name="Cylinder010"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder010.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder010_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder010_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp069"
            position={[-1.76, -0.289, -2.666]}
            rotation={[-Math.PI, 0, 0]}
            scale={-0.012}
          >
            <mesh
              name="Cylinder010"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder010.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder010_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder010_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp070"
            position={[-1.76, -0.289, -2.036]}
            rotation={[-Math.PI, 0, 0]}
            scale={-0.012}
          >
            <mesh
              name="Cylinder010"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder010.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder010_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder010_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp071"
            position={[-1.973, -0.294, -0.673]}
            rotation={[-Math.PI, 0, 0]}
            scale={-0.012}
          >
            <mesh
              name="Cylinder010"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder010.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder010_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder010_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp072"
            position={[-1.973, -0.294, 0.458]}
            rotation={[-Math.PI, 0, 0]}
            scale={-0.012}
          >
            <mesh
              name="Cylinder010"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder010.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder010_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder010_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp073"
            position={[-1.973, -0.294, 1.641]}
            rotation={[-Math.PI, 0, 0]}
            scale={-0.012}
          >
            <mesh
              name="Cylinder010"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder010.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder010_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder010_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp074"
            position={[-2.481, -0.032, 2.725]}
            rotation={[-Math.PI, 0, 0]}
            scale={-0.012}
          >
            <mesh
              name="Cylinder010"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder010.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder010_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder010_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp075"
            position={[-2.481, -0.032, 3.885]}
            rotation={[-Math.PI, 0, 0]}
            scale={-0.012}
          >
            <mesh
              name="Cylinder010"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder010.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder010_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder010_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp076"
            position={[-3.479, -0.032, 6.13]}
            rotation={[-Math.PI, -1.571, 0]}
            scale={-0.012}
          >
            <mesh
              name="Cylinder011"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder011.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder011_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder011_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp077"
            position={[-5.121, -0.032, 6.13]}
            rotation={[-Math.PI, -1.571, 0]}
            scale={-0.012}
          >
            <mesh
              name="Cylinder011"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder011.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder011_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder011_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp078"
            position={[-4.522, -0.032, 6.13]}
            rotation={[-Math.PI, -1.571, 0]}
            scale={-0.012}
          >
            <mesh
              name="Cylinder011"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder011.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder011_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder011_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp079"
            position={[5.212, 0.028, 6.666]}
            rotation={[0, -1.571, 0]}
            scale={0.024}
          >
            <mesh
              name="Cylinder002"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder002.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder002_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder002_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp080"
            position={[1.794, -0.179, 6.668]}
            rotation={[0, -1.571, 0]}
            scale={0.024}
          >
            <mesh
              name="Cylinder002"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder002.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder002_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder002_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp081"
            position={[-0.79, 0.028, 6.668]}
            rotation={[0, -1.571, 0]}
            scale={0.024}
          >
            <mesh
              name="Cylinder002"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder002.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder002_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder002_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="IM_Lamp082"
            position={[-3.373, 0.172, 6.668]}
            rotation={[0, -1.571, 0]}
            scale={0.024}
          >
            <mesh
              name="Cylinder002"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder002.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder002_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder002_1.geometry}
              material={materials["light.002"]}
            />
          </group>
          <group
            name="SM_Lamp_01001"
            position={[-5.957, 0.172, 6.668]}
            rotation={[0, -1.571, 0]}
            scale={0.024}
          >
            <mesh
              name="Cylinder002"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder002.geometry}
              material={materials["lamp.002"]}
            />
            <mesh
              name="Cylinder002_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder002_1.geometry}
              material={materials["light.002"]}
            />
          </group>
        </group>
      </group>
    </group>
    </>

  );
}

useGLTF.preload("/FinalModel.glb");

